"""Apply the placement question-bank table to an existing pre-baseline database.

Use this only for local databases whose Alembic version still points at the archived
0060/0061 migration chain. It creates the new table/indexes if missing and does not
touch alembic_version or existing user data.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import text

from app.db.session import engine


DDL_STATEMENTS = [
"""
CREATE TABLE IF NOT EXISTS public.language_placement_question_bank_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id integer NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
    skill character varying(32) NOT NULL,
    level public.language_level NOT NULL,
    boundary_low_level public.language_level,
    boundary_high_level public.language_level,
    subskill character varying(64),
    question_type character varying(32) DEFAULT 'mcq' NOT NULL,
    prompt_text text NOT NULL,
    passage text,
    situation text,
    options_json jsonb,
    correct_index integer,
    explanation text,
    media_object_id integer REFERENCES public.media_objects(id) ON DELETE SET NULL,
    audio_meta_json jsonb,
    body_json jsonb,
    stable_key character varying(160) UNIQUE,
    source character varying(32) DEFAULT 'ai_generated' NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    reviewer_note text,
    usage_count integer DEFAULT 0 NOT NULL,
    correct_count integer DEFAULT 0 NOT NULL,
    difficulty_estimate double precision,
    discrimination_estimate double precision,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
)
""",
"""
CREATE INDEX IF NOT EXISTS ix_lpq_bank_lookup
    ON public.language_placement_question_bank_items
    (language_id, skill, level, is_verified, is_active)
""",
"""
CREATE INDEX IF NOT EXISTS ix_lpq_bank_boundary
    ON public.language_placement_question_bank_items
    (language_id, skill, boundary_low_level, boundary_high_level, is_verified, is_active)
""",
"""
CREATE INDEX IF NOT EXISTS ix_language_placement_question_bank_items_language_id
    ON public.language_placement_question_bank_items (language_id)
""",
"""
CREATE INDEX IF NOT EXISTS ix_language_placement_question_bank_items_level
    ON public.language_placement_question_bank_items (level)
""",
"""
CREATE INDEX IF NOT EXISTS ix_language_placement_question_bank_items_skill
    ON public.language_placement_question_bank_items (skill)
""",
"""
CREATE INDEX IF NOT EXISTS ix_language_placement_question_bank_items_subskill
    ON public.language_placement_question_bank_items (subskill)
""",
]


async def main() -> int:
    async with engine.begin() as conn:
        for statement in DDL_STATEMENTS:
            await conn.execute(text(statement))
    print("placement question-bank table/indexes are ready")
    await engine.dispose()
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
