"""Writing goal profile catalog (W2.1 frozen) — complete educational profiles."""

from __future__ import annotations

from app.services.language_writing.enums import (
    ExpectedWritingOutput,
    LexisCategory,
    WritingCoachPersonality,
    WritingCoachTone,
    WritingFeedbackStyle,
    WritingGoal,
    WritingMissionStyle,
    WritingPromotionStyle,
    WritingRevisionStyle,
)
from app.services.language_writing_curriculum.types import WritingCoachDefaults, WritingGoalProfile

WRITING_GOAL_KEY = "writing_goal"
GOAL_PROFILE_VERSION = "2.1.0"

_EO = ExpectedWritingOutput
_LC = LexisCategory
_MS = WritingMissionStyle
_PS = WritingPromotionStyle
_RS = WritingRevisionStyle
_CT = WritingCoachTone

_PROFILES: dict[WritingGoal, WritingGoalProfile] = {
    WritingGoal.general_english: WritingGoalProfile(
        goal=WritingGoal.general_english,
        label="General English",
        preferred_task_types=("describe", "explain", "narrate", "opinion", "request"),
        preferred_genres=("paragraph", "message", "short_email", "story"),
        preferred_mission_style=_MS.everyday_scenario,
        preferred_writing_outputs=(_EO.paragraph, _EO.message, _EO.email, _EO.story),
        preferred_vocabulary_categories=(_LC.core, _LC.topic, _LC.common_phrases, _LC.collocations),
        preferred_grammar_priorities=("present_simple", "past_simple", "linking_words", "because"),
        preferred_coach_tone=_CT.warm,
        preferred_revision_style=_RS.gentle_scaffold,
        preferred_promotion_style=_PS.gradual,
        register="neutral",
        vocabulary_style="Balanced everyday English with topic-appropriate lexis",
        feedback_emphasis=("clarity", "coherence", "grammar", "vocabulary"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.friendly_teacher,
            feedback_style=WritingFeedbackStyle.supportive,
            revision_strictness=0.4,
        ),
        feedback_style=WritingFeedbackStyle.supportive,
        coach_personality_id=WritingCoachPersonality.friendly_teacher.value,
        preferred_topic_ids=("daily_life", "family", "food", "entertainment"),
        knowledge_chain_preferences=("daily_routines", "family_introductions"),
        style_directives=(
            "Use clear, practical writing tasks from everyday life.",
            "Balance accuracy with communicative success.",
            "Encourage revision without exam pressure.",
        ),
        vocabulary_category_weights={
            _LC.core.value: 0.35,
            _LC.topic.value: 0.30,
            _LC.common_phrases.value: 0.20,
            _LC.collocations.value: 0.15,
        },
        wpa_task_bundle_key="general_english_wpa",
    ),
    WritingGoal.travel: WritingGoalProfile(
        goal=WritingGoal.travel,
        label="Travel",
        preferred_task_types=("describe", "request", "complaint", "confirm", "guide", "review"),
        preferred_genres=("message", "email_short", "formal_email", "paragraph", "review"),
        preferred_mission_style=_MS.travel_scenario,
        preferred_writing_outputs=(_EO.message, _EO.email, _EO.review, _EO.paragraph),
        preferred_vocabulary_categories=(_LC.topic, _LC.common_phrases, _LC.core, _LC.collocations),
        preferred_grammar_priorities=("polite_requests", "past_simple", "imperatives", "sequencers"),
        preferred_coach_tone=_CT.warm,
        preferred_revision_style=_RS.one_priority_per_turn,
        preferred_promotion_style=_PS.competency_checklist,
        register="polite_service",
        vocabulary_style="Practical travel and service vocabulary — airports, hotels, transport",
        feedback_emphasis=("politeness", "clarity", "problem_explanation", "register"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.friendly_teacher,
            feedback_style=WritingFeedbackStyle.supportive,
            revision_strictness=0.45,
        ),
        feedback_style=WritingFeedbackStyle.supportive,
        coach_personality_id=WritingCoachPersonality.friendly_teacher.value,
        preferred_topic_ids=("travel", "services", "shopping"),
        knowledge_chain_preferences=("travel_airport_journey", "travel_hotel_stay"),
        style_directives=(
            "Favor real travel scenarios: check-in, delays, directions, complaints, reviews.",
            "Emphasize polite requests and clear problem statements.",
            "Use service-register vocabulary without sounding artificial.",
        ),
        vocabulary_category_weights={
            _LC.topic.value: 0.35,
            _LC.common_phrases.value: 0.30,
            _LC.core.value: 0.25,
            _LC.collocations.value: 0.10,
        },
        wpa_task_bundle_key="travel_wpa",
    ),
    WritingGoal.business: WritingGoalProfile(
        goal=WritingGoal.business,
        label="Business",
        preferred_task_types=("request", "follow_up", "proposal", "report", "introduce", "confirm"),
        preferred_genres=("business_email", "memo", "report", "formal_email"),
        preferred_mission_style=_MS.business_brief,
        preferred_writing_outputs=(_EO.email, _EO.report, _EO.summary, _EO.paragraph),
        preferred_vocabulary_categories=(_LC.business, _LC.collocations, _LC.common_phrases, _LC.core),
        preferred_grammar_priorities=("polite_requests", "passive_voice", "linking_words", "modal_verbs"),
        preferred_coach_tone=_CT.professional,
        preferred_revision_style=_RS.iterative_polish,
        preferred_promotion_style=_PS.competency_checklist,
        register="professional",
        vocabulary_style="Business collocations, formal requests, and workplace tone",
        feedback_emphasis=("professional_tone", "organization", "action_items", "register"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.business_mentor,
            feedback_style=WritingFeedbackStyle.professional,
            revision_strictness=0.55,
        ),
        feedback_style=WritingFeedbackStyle.professional,
        coach_personality_id=WritingCoachPersonality.business_mentor.value,
        preferred_topic_ids=("business", "work", "technology", "communication"),
        knowledge_chain_preferences=("business_email_flow", "workplace_updates"),
        style_directives=(
            "Use workplace-realistic emails, memos, and short reports.",
            "Prioritize clarity, action items, and professional register.",
            "Coach should sound like a mentor, not a manager grading KPIs.",
        ),
        vocabulary_category_weights={
            _LC.business.value: 0.35,
            _LC.collocations.value: 0.25,
            _LC.common_phrases.value: 0.20,
            _LC.core.value: 0.20,
        },
        wpa_task_bundle_key="business_wpa",
    ),
    WritingGoal.ielts: WritingGoalProfile(
        goal=WritingGoal.ielts,
        label="IELTS",
        preferred_task_types=("describe", "explain", "opinion", "compare", "report", "argue"),
        preferred_genres=("essay", "report", "academic_paragraph", "formal_email"),
        preferred_mission_style=_MS.exam_task,
        preferred_writing_outputs=(_EO.essay, _EO.report, _EO.paragraph, _EO.email),
        preferred_vocabulary_categories=(_LC.academic, _LC.collocations, _LC.topic, _LC.core),
        preferred_grammar_priorities=("linking_words", "complex_sentences", "passive_voice", "cause_effect"),
        preferred_coach_tone=_CT.exam_calibrated,
        preferred_revision_style=_RS.exam_rigor,
        preferred_promotion_style=_PS.exam_gate,
        register="academic_exam",
        vocabulary_style="Academic lexis, precise collocations, and exam-appropriate range",
        feedback_emphasis=("task_response", "coherence", "lexical_resource", "grammar_range"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.ielts_coach,
            feedback_style=WritingFeedbackStyle.exam_focused,
            revision_strictness=0.65,
        ),
        feedback_style=WritingFeedbackStyle.exam_focused,
        coach_personality_id=WritingCoachPersonality.ielts_coach.value,
        preferred_topic_ids=("education", "environment", "society", "technology", "health"),
        knowledge_chain_preferences=("education_school_life", "environment_issues"),
        style_directives=(
            "Mirror IELTS Task 1/2 expectations: clear position, supported ideas, formal register.",
            "Coach references task achievement and coherence — never raw band scores in student copy.",
            "Use exam-realistic prompts with structured organization scaffolds at lower CEFR.",
        ),
        time_limit_minutes=40,
        vocabulary_category_weights={
            _LC.academic.value: 0.35,
            _LC.collocations.value: 0.25,
            _LC.topic.value: 0.25,
            _LC.core.value: 0.15,
        },
        wpa_task_bundle_key="ielts_wpa",
    ),
    WritingGoal.academic: WritingGoalProfile(
        goal=WritingGoal.academic,
        label="Academic",
        preferred_task_types=("explain", "argue", "report", "compare", "summary", "propose"),
        preferred_genres=("essay", "academic_paragraph", "report", "summary"),
        preferred_mission_style=_MS.academic_task,
        preferred_writing_outputs=(_EO.essay, _EO.report, _EO.summary, _EO.paragraph),
        preferred_vocabulary_categories=(_LC.academic, _LC.collocations, _LC.topic, _LC.core),
        preferred_grammar_priorities=("linking_words", "passive_voice", "relative_clauses", "cause_effect"),
        preferred_coach_tone=_CT.direct,
        preferred_revision_style=_RS.exam_rigor,
        preferred_promotion_style=_PS.exam_gate,
        register="academic",
        vocabulary_style="Discipline-neutral academic vocabulary and hedging language",
        feedback_emphasis=("argument_structure", "evidence", "formality", "paragraph_unity"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.academic_tutor,
            feedback_style=WritingFeedbackStyle.direct,
            revision_strictness=0.60,
        ),
        feedback_style=WritingFeedbackStyle.direct,
        coach_personality_id=WritingCoachPersonality.academic_tutor.value,
        preferred_topic_ids=("education", "science", "society", "history", "culture"),
        knowledge_chain_preferences=("education_school_life", "science_discovery"),
        style_directives=(
            "Build toward university-style paragraphs and short essays.",
            "Emphasize thesis, support, and academic connectors.",
            "Coach explains why structure matters — not just what to fix.",
        ),
        vocabulary_category_weights={
            _LC.academic.value: 0.40,
            _LC.collocations.value: 0.25,
            _LC.topic.value: 0.20,
            _LC.core.value: 0.15,
        },
        wpa_task_bundle_key="academic_wpa",
    ),
    WritingGoal.job_interview: WritingGoalProfile(
        goal=WritingGoal.job_interview,
        label="Job Interview",
        preferred_task_types=("introduce", "describe", "explain", "application", "follow_up"),
        preferred_genres=("paragraph", "formal_email", "cover_letter", "message"),
        preferred_mission_style=_MS.interview_prep,
        preferred_writing_outputs=(_EO.paragraph, _EO.email, _EO.message, _EO.summary),
        preferred_vocabulary_categories=(_LC.business, _LC.collocations, _LC.core, _LC.common_phrases),
        preferred_grammar_priorities=("present_perfect", "past_simple", "modal_verbs", "linking_words"),
        preferred_coach_tone=_CT.professional,
        preferred_revision_style=_RS.one_priority_per_turn,
        preferred_promotion_style=_PS.interview_readiness,
        register="professional_personal",
        vocabulary_style="Professional self-presentation and achievement vocabulary",
        feedback_emphasis=("clarity", "confidence", "specific_examples", "professional_tone"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.business_mentor,
            feedback_style=WritingFeedbackStyle.professional,
            revision_strictness=0.50,
        ),
        feedback_style=WritingFeedbackStyle.professional,
        coach_personality_id=WritingCoachPersonality.business_mentor.value,
        preferred_topic_ids=("work", "business", "education", "technology"),
        knowledge_chain_preferences=("work_career_intro", "business_email_flow"),
        style_directives=(
            "Focus on self-introduction, strengths, and professional follow-up messages.",
            "Coach helps students sound confident without exaggeration.",
            "Use STAR-style examples where natural (situation, task, action, result).",
        ),
        vocabulary_category_weights={
            _LC.business.value: 0.30,
            _LC.collocations.value: 0.25,
            _LC.core.value: 0.25,
            _LC.common_phrases.value: 0.20,
        },
        wpa_task_bundle_key="job_interview_wpa",
    ),
    WritingGoal.creative_writing: WritingGoalProfile(
        goal=WritingGoal.creative_writing,
        label="Creative Writing",
        preferred_task_types=("narrate", "describe", "reflect", "dialogue", "review"),
        preferred_genres=("story", "dialogue_paragraph", "review", "article"),
        preferred_mission_style=_MS.creative_prompt,
        preferred_writing_outputs=(_EO.story, _EO.dialogue, _EO.review, _EO.article),
        preferred_vocabulary_categories=(_LC.topic, _LC.idioms, _LC.collocations, _LC.core),
        preferred_grammar_priorities=("past_simple", "adjectives", "sequencers", "dialogue_punctuation"),
        preferred_coach_tone=_CT.creative,
        preferred_revision_style=_RS.creative_craft,
        preferred_promotion_style=_PS.portfolio_milestone,
        register="expressive",
        vocabulary_style="Descriptive adjectives, sensory language, and narrative flow",
        feedback_emphasis=("voice", "imagery", "pacing", "engagement"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.creative_writing_coach,
            feedback_style=WritingFeedbackStyle.creative,
            revision_strictness=0.35,
        ),
        feedback_style=WritingFeedbackStyle.creative,
        coach_personality_id=WritingCoachPersonality.creative_writing_coach.value,
        preferred_topic_ids=("entertainment", "culture", "travel", "family", "food"),
        knowledge_chain_preferences=("creative_story_starter", "entertainment_review"),
        style_directives=(
            "Encourage voice and creativity — grammar serves the story.",
            "Coach celebrates strengths before suggesting one craft improvement.",
            "Avoid exam-style tone; use mentor-of-creativity voice.",
        ),
        vocabulary_category_weights={
            _LC.topic.value: 0.30,
            _LC.idioms.value: 0.15,
            _LC.collocations.value: 0.25,
            _LC.core.value: 0.30,
        },
        wpa_task_bundle_key="creative_wpa",
    ),
    WritingGoal.daily_communication: WritingGoalProfile(
        goal=WritingGoal.daily_communication,
        label="Daily Communication",
        preferred_task_types=("request", "thank", "invite", "respond", "explain_simple"),
        preferred_genres=("message", "short_note", "email_short", "paragraph"),
        preferred_mission_style=_MS.quick_message,
        preferred_writing_outputs=(_EO.message, _EO.email, _EO.paragraph),
        preferred_vocabulary_categories=(_LC.common_phrases, _LC.core, _LC.topic, _LC.collocations),
        preferred_grammar_priorities=("present_simple", "imperatives", "questions", "polite_requests"),
        preferred_coach_tone=_CT.energetic,
        preferred_revision_style=_RS.concise_pass,
        preferred_promotion_style=_PS.gradual,
        register="informal_neutral",
        vocabulary_style="High-frequency phrases for texting, notes, and short messages",
        feedback_emphasis=("brevity", "clarity", "natural_phrasing", "politeness"),
        coach_defaults=WritingCoachDefaults(
            personality=WritingCoachPersonality.friendly_teacher,
            feedback_style=WritingFeedbackStyle.concise,
            revision_strictness=0.35,
        ),
        feedback_style=WritingFeedbackStyle.concise,
        coach_personality_id=WritingCoachPersonality.friendly_teacher.value,
        preferred_topic_ids=("daily_life", "communication", "family", "shopping"),
        knowledge_chain_preferences=("daily_messages", "family_introductions"),
        style_directives=(
            "Keep tasks short and practical — messages, notes, quick emails.",
            "Coach prioritizes getting the message across over essay structure.",
            "Use everyday phrasing students will actually send.",
        ),
        word_target_multiplier=0.85,
        vocabulary_category_weights={
            _LC.common_phrases.value: 0.35,
            _LC.core.value: 0.35,
            _LC.topic.value: 0.20,
            _LC.collocations.value: 0.10,
        },
        wpa_task_bundle_key="daily_communication_wpa",
    ),
}


def all_writing_goal_profiles() -> tuple[WritingGoalProfile, ...]:
    return tuple(_PROFILES[g] for g in WritingGoal)


def profile_for_goal(goal: WritingGoal) -> WritingGoalProfile:
    return _PROFILES[goal]
