"""Self-contained Grammar & Vocabulary teaching lessons per CEFR level.

The platform mostly *corrects* the student. These lessons close the teaching gap:
each lesson EXPLAINS one grammar point or one vocabulary set in clear English at the
level, with examples and a tiny practice.

Lessons are auto-generated by the LLM (cached per level) and always fall back to a
curated, CEFR-aligned set so they are reliable and "studied" even with no AI.

Mirrors the structure/style of ``language_curriculum_service`` (curated dict, _parse,
TTL cache, AI fallback) and reuses its way of resolving the student's level.
"""

from __future__ import annotations

import json
import logging
import re
import time

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.language.analytics import LanguageAnalytics
from app.models.language.enums import LanguageLevel
from app.services.ai_service import generate_llm_json
from app.services.claude_service import is_claude_configured
from app.services.language_level_utils import bottleneck_level
from app.services.language_subscription_service import get_default_language

logger = logging.getLogger(__name__)
settings = get_settings()

LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"]
TYPES = ("grammar", "vocabulary")

# Curated CEFR set — the reliable, well-studied base (and the AI fallback).
# ~3 grammar + 2 vocabulary lessons per level. Real, teachable content.
CURATED_LESSONS: dict[str, list[dict]] = {
    "A1": [
        {
            "type": "grammar",
            "title": "Present Simple (everyday facts and routines)",
            "explanation": (
                "We use the present simple to talk about facts, habits, and routines — "
                "things that are generally or always true. With I/you/we/they the verb does "
                "not change (I work). With he/she/it we add -s (she works)."
            ),
            "examples": [
                "I live in Berlin.",
                "She works in a hospital.",
                "We play football on Sundays.",
                "He drinks coffee every morning.",
            ],
            "practice": [
                {"question": "She ___ (read) every night.", "answer": "reads"},
                {"question": "They ___ (live) in Spain.", "answer": "live"},
                {"question": "He ___ (go) to school by bus.", "answer": "goes"},
            ],
        },
        {
            "type": "grammar",
            "title": "Articles a / an",
            "explanation": (
                "Use 'a' before a word that starts with a consonant sound (a book, a car) "
                "and 'an' before a word that starts with a vowel sound (an apple, an hour). "
                "It is about the sound, not the letter."
            ),
            "examples": [
                "I have a dog.",
                "She is an engineer.",
                "It is an honest answer.",
                "He bought a university hat.",
            ],
            "practice": [
                {"question": "I ate ___ orange.", "answer": "an"},
                {"question": "She has ___ cat.", "answer": "a"},
                {"question": "He waited for ___ hour.", "answer": "an"},
            ],
        },
        {
            "type": "grammar",
            "title": "Plural Nouns",
            "explanation": (
                "Most nouns add -s to become plural (book -> books). Add -es after s, x, ch, sh "
                "(box -> boxes). If a noun ends in consonant + y, change y to -ies (city -> cities). "
                "Some are irregular (child -> children, man -> men)."
            ),
            "examples": [
                "one car, two cars",
                "one box, three boxes",
                "one baby, four babies",
                "one child, two children",
            ],
            "practice": [
                {"question": "Plural of 'bus'.", "answer": "buses"},
                {"question": "Plural of 'country'.", "answer": "countries"},
                {"question": "Plural of 'woman'.", "answer": "women"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Family Members",
            "explanation": (
                "These words describe the people in a family. Learn them in pairs (male/female) "
                "so they are easy to remember."
            ),
            "examples": [
                "mother / father — your parents",
                "sister / brother — your siblings",
                "grandmother / grandfather — your grandparents",
                "aunt / uncle, cousin",
            ],
            "practice": [
                {"question": "The mother of your mother is your ___.", "answer": "grandmother"},
                {"question": "Your father's brother is your ___.", "answer": "uncle"},
                {"question": "Your parents' children together are ___.", "answer": "siblings"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Numbers 1–20",
            "explanation": (
                "Numbers are essential for prices, time, and age. Learn 1–12 first, then notice "
                "the pattern in the 'teens' (thirteen, fourteen ...)."
            ),
            "examples": [
                "1 one, 2 two, 3 three, 4 four, 5 five",
                "11 eleven, 12 twelve, 13 thirteen",
                "15 fifteen, 18 eighteen, 20 twenty",
                "I am twenty years old.",
            ],
            "practice": [
                {"question": "Write the number 12 in words.", "answer": "twelve"},
                {"question": "Write the number 15 in words.", "answer": "fifteen"},
                {"question": "Write the number 20 in words.", "answer": "twenty"},
            ],
        },
    ],
    "A2": [
        {
            "type": "grammar",
            "title": "Past Simple (regular and irregular)",
            "explanation": (
                "Use the past simple to talk about finished actions in the past. Regular verbs "
                "add -ed (work -> worked). Many common verbs are irregular and must be learned "
                "(go -> went, see -> saw, have -> had)."
            ),
            "examples": [
                "Yesterday I visited my friend.",
                "We watched a film last night.",
                "She went to the market.",
                "They saw a great show.",
            ],
            "practice": [
                {"question": "Last week she ___ (travel) to Rome.", "answer": "travelled"},
                {"question": "I ___ (go) to the doctor yesterday.", "answer": "went"},
                {"question": "We ___ (see) a film last night.", "answer": "saw"},
            ],
        },
        {
            "type": "grammar",
            "title": "Comparatives",
            "explanation": (
                "Use comparatives to compare two things. For short adjectives add -er + than "
                "(cheaper than). For long adjectives use 'more ... than' (more expensive than). "
                "Some are irregular: good -> better, bad -> worse."
            ),
            "examples": [
                "This book is cheaper than that one.",
                "A car is more expensive than a bike.",
                "Today is hotter than yesterday.",
                "Her work is better than mine.",
            ],
            "practice": [
                {"question": "Big: 'A house is ___ a flat.'", "answer": "bigger than"},
                {"question": "Beautiful: 'This park is ___ that one.'", "answer": "more beautiful than"},
                {"question": "Good: 'Tea is ___ coffee for me.'", "answer": "better than"},
            ],
        },
        {
            "type": "grammar",
            "title": "Future: going to",
            "explanation": (
                "Use 'be going to + verb' for plans and intentions you have already decided. "
                "Form: am/is/are + going to + base verb."
            ),
            "examples": [
                "I am going to travel next week.",
                "She is going to study medicine.",
                "We are going to buy a new car.",
                "They are not going to come.",
            ],
            "practice": [
                {"question": "I ___ (visit) my aunt tomorrow.", "answer": "am going to visit"},
                {"question": "They ___ (start) a business.", "answer": "are going to start"},
                {"question": "He ___ (not / work) on Sunday.", "answer": "is not going to work"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Food and Drink",
            "explanation": (
                "Words for common food and drink help you shop and order in a restaurant. "
                "Notice that some foods are uncountable (rice, water, bread)."
            ),
            "examples": [
                "fruit: apple, banana, orange",
                "vegetables: carrot, potato, onion",
                "drinks: water, juice, coffee, tea",
                "I would like some bread and cheese.",
            ],
            "practice": [
                {"question": "Name a red fruit.", "answer": "apple"},
                {"question": "A hot drink made from beans.", "answer": "coffee"},
                {"question": "We bake this and eat it every day.", "answer": "bread"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Travel and Transport",
            "explanation": (
                "Travel vocabulary helps you move around a city or country. Learn the place "
                "(airport, station) and the transport (plane, train) together."
            ),
            "examples": [
                "by plane / at the airport",
                "by train / at the station",
                "by bus / at the bus stop",
                "I need a ticket to the city centre.",
            ],
            "practice": [
                {"question": "You catch a plane at the ___.", "answer": "airport"},
                {"question": "You buy this to travel by train.", "answer": "ticket"},
                {"question": "A train stops at a ___.", "answer": "station"},
            ],
        },
    ],
    "B1": [
        {
            "type": "grammar",
            "title": "Present Perfect vs Past Simple",
            "explanation": (
                "Use the past simple for finished actions at a specific past time (I saw it "
                "yesterday). Use the present perfect (have/has + past participle) for life "
                "experiences or recent actions with a result now, without a specific time "
                "(I have seen it)."
            ),
            "examples": [
                "I have been to Italy twice.",
                "She has just finished her homework.",
                "We went to Paris in 2019.",
                "Have you ever eaten sushi?",
            ],
            "practice": [
                {"question": "I ___ (never / try) skiing.", "answer": "have never tried"},
                {"question": "She ___ (visit) Spain last summer.", "answer": "visited"},
                {"question": "___ you ever ___ (meet) a celebrity?", "answer": "Have ... met"},
            ],
        },
        {
            "type": "grammar",
            "title": "First and Second Conditional",
            "explanation": (
                "First conditional talks about real future possibilities: If + present simple, "
                "will + verb (If it rains, I will stay home). Second conditional talks about "
                "unreal or imaginary situations: If + past simple, would + verb (If I had time, "
                "I would study more)."
            ),
            "examples": [
                "If it rains, we will cancel the trip.",
                "If I had money, I would travel the world.",
                "If you study, you will pass.",
                "If she were here, she would help us.",
            ],
            "practice": [
                {"question": "If you heat ice, it ___ (melt).", "answer": "will melt"},
                {"question": "If I ___ (be) you, I would apologise.", "answer": "were"},
                {"question": "She would call if she ___ (have) your number.", "answer": "had"},
            ],
        },
        {
            "type": "grammar",
            "title": "Connectors: although / because / so",
            "explanation": (
                "Connectors link ideas. Use 'because' to give a reason, 'so' to give a result, "
                "and 'although' to show a contrast (an unexpected combination of ideas)."
            ),
            "examples": [
                "I stayed home because I was tired.",
                "It was late, so we left.",
                "Although it was raining, we went out.",
                "I like reading because it builds vocabulary.",
            ],
            "practice": [
                {"question": "'___ he is rich, he is not happy.' (contrast)", "answer": "Although"},
                {"question": "'I was hungry, ___ I ate.' (result)", "answer": "so"},
                {"question": "'I left ___ I was tired.' (reason)", "answer": "because"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Work and Jobs",
            "explanation": (
                "Vocabulary for the world of work lets you describe your job and career. "
                "Learn the job, the place of work, and a key verb together."
            ),
            "examples": [
                "apply for a job / send a CV",
                "colleague, manager, salary",
                "full-time / part-time / freelance",
                "I work as an accountant in an office.",
            ],
            "practice": [
                {"question": "The money you earn each month is your ___.", "answer": "salary"},
                {"question": "A person you work with is a ___.", "answer": "colleague"},
                {"question": "To ___ for a job, you send your CV.", "answer": "apply"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Health and the Body",
            "explanation": (
                "Health vocabulary helps you describe problems and visit a doctor. Learn the "
                "symptom, the body part, and what the doctor does."
            ),
            "examples": [
                "I have a headache / a sore throat.",
                "symptoms: cough, fever, pain",
                "The doctor gives a prescription.",
                "You should rest and drink water.",
            ],
            "practice": [
                {"question": "A pain in your head is a ___.", "answer": "headache"},
                {"question": "A high body temperature is a ___.", "answer": "fever"},
                {"question": "A doctor writes this so you can get medicine.", "answer": "prescription"},
            ],
        },
    ],
    "B2": [
        {
            "type": "grammar",
            "title": "The Passive Voice",
            "explanation": (
                "Use the passive when the action matters more than who does it, or the doer is "
                "unknown. Form: be (in the right tense) + past participle. The object of the "
                "active sentence becomes the subject."
            ),
            "examples": [
                "The bridge was built in 1890.",
                "English is spoken all over the world.",
                "The report will be finished tomorrow.",
                "My car has been repaired.",
            ],
            "practice": [
                {"question": "Make passive: 'They build houses here.'", "answer": "Houses are built here."},
                {"question": "Make passive: 'Someone stole my bike.'", "answer": "My bike was stolen."},
                {"question": "Make passive: 'They will announce the results.'", "answer": "The results will be announced."},
            ],
        },
        {
            "type": "grammar",
            "title": "Reported Speech",
            "explanation": (
                "When we report what someone said, we usually move the tense one step back "
                "(present -> past) and change pronouns and time words. 'say' has no object; "
                "'tell' needs one (tell me)."
            ),
            "examples": [
                "She said she was tired.",
                "He told me he had finished.",
                "They said they would come the next day.",
                "I said I could help.",
            ],
            "practice": [
                {"question": "Report: 'I am busy.' (She said ...)", "answer": "She said she was busy."},
                {"question": "Report: 'We will call you.' (They said ...)", "answer": "They said they would call me."},
                {"question": "Report: 'I have seen it.' (He said ...)", "answer": "He said he had seen it."},
            ],
        },
        {
            "type": "grammar",
            "title": "Relative Clauses",
            "explanation": (
                "Relative clauses add information about a noun. Use 'who' for people, 'which' "
                "for things, 'that' for both, 'where' for places, and 'whose' for possession. "
                "Non-defining clauses (extra information) take commas."
            ),
            "examples": [
                "The man who called you is my boss.",
                "This is the book that I told you about.",
                "Paris, which is in France, is beautiful.",
                "That's the house where I grew up.",
            ],
            "practice": [
                {"question": "'The woman ___ lives next door is a doctor.'", "answer": "who"},
                {"question": "'The phone ___ I bought is broken.'", "answer": "that / which"},
                {"question": "'That's the city ___ I was born.'", "answer": "where"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Idioms and Collocations",
            "explanation": (
                "Idioms are fixed expressions with a non-literal meaning; collocations are words "
                "that naturally go together. Using them makes your English sound natural."
            ),
            "examples": [
                "Let's get to the point. (= speak directly)",
                "make a decision (not 'do a decision')",
                "It's a piece of cake. (= very easy)",
                "heavy rain, strong coffee (collocations)",
            ],
            "practice": [
                {"question": "We ___ a decision, we don't 'do' one.", "answer": "make"},
                {"question": "'A piece of cake' means it is very ___.", "answer": "easy"},
                {"question": "Rain that is very strong is ___ rain.", "answer": "heavy"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Environment and Current Affairs",
            "explanation": (
                "These words let you discuss news, society, and the environment — common B2 "
                "topics in exams and discussions."
            ),
            "examples": [
                "climate change, pollution, recycling",
                "renewable energy, carbon footprint",
                "economy, government, policy",
                "We must reduce our carbon footprint.",
            ],
            "practice": [
                {"question": "Energy from the sun and wind is ___ energy.", "answer": "renewable"},
                {"question": "Reusing materials instead of throwing them away is ___.", "answer": "recycling"},
                {"question": "Dirty air and water is a form of ___.", "answer": "pollution"},
            ],
        },
    ],
    "C1": [
        {
            "type": "grammar",
            "title": "Inversion for Emphasis",
            "explanation": (
                "For emphasis or a formal style, we can put a negative or limiting adverb at the "
                "start of a sentence and then invert the subject and auxiliary verb (like a "
                "question). Common starters: Never, Rarely, Not only, No sooner, Hardly."
            ),
            "examples": [
                "Never have I seen such a mess.",
                "Not only did she sing, but she also danced.",
                "Rarely do we get such an opportunity.",
                "No sooner had he left than it started to rain.",
            ],
            "practice": [
                {"question": "Invert: 'I have never been so happy.'", "answer": "Never have I been so happy."},
                {"question": "Invert: 'We rarely see this.'", "answer": "Rarely do we see this."},
                {"question": "Start with 'Not only': 'She is clever and kind.'", "answer": "Not only is she clever, but she is also kind."},
            ],
        },
        {
            "type": "grammar",
            "title": "Mixed Conditionals",
            "explanation": (
                "Mixed conditionals link two different times. A past condition with a present "
                "result: If I had studied medicine, I would be a doctor now. A present condition "
                "with a past result: If I weren't so shy, I would have spoken to her."
            ),
            "examples": [
                "If I had saved money, I would be rich now.",
                "If she were more careful, she wouldn't have crashed.",
                "If we had left earlier, we would be there by now.",
                "If he weren't afraid of flying, he would have visited us.",
            ],
            "practice": [
                {"question": "If I ___ (take) that job, I would be in Tokyo now.", "answer": "had taken"},
                {"question": "If you weren't so busy, you ___ (come) yesterday.", "answer": "would have come"},
                {"question": "If they had invested then, they ___ (be) wealthy today.", "answer": "would be"},
            ],
        },
        {
            "type": "grammar",
            "title": "Hedging and Cautious Language",
            "explanation": (
                "In academic and professional English we soften claims to sound objective and "
                "polite. Use modal verbs (may, might, could), and phrases like 'it appears that', "
                "'tends to', 'is likely to', 'to some extent'."
            ),
            "examples": [
                "This may suggest a link between the two.",
                "The results tend to support the theory.",
                "It could be argued that the policy failed.",
                "Prices are likely to rise.",
            ],
            "practice": [
                {"question": "Soften: 'This proves the theory.' (use 'suggest')", "answer": "This appears to suggest the theory."},
                {"question": "Soften: 'It will rain.' (use 'likely')", "answer": "It is likely to rain."},
                {"question": "Add a hedge: 'The plan failed.' (use 'could be argued')", "answer": "It could be argued that the plan failed."},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Academic and Formal Vocabulary",
            "explanation": (
                "C1 writing replaces everyday words with more precise, formal ones. Learn these "
                "upgrades to lift your register in essays and reports."
            ),
            "examples": [
                "get -> obtain / acquire",
                "show -> demonstrate / illustrate",
                "a lot of -> a significant amount of",
                "Moreover, the evidence demonstrates a clear trend.",
            ],
            "practice": [
                {"question": "A formal word for 'get' (receive).", "answer": "obtain"},
                {"question": "A formal word for 'show' (evidence).", "answer": "demonstrate"},
                {"question": "A formal linker meaning 'also'.", "answer": "moreover / furthermore"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Nuance: Connotation and Precision",
            "explanation": (
                "Near-synonyms carry different shades of meaning (connotation). Choosing the "
                "exact word shows control. Notice the positive/negative or formal/neutral feel."
            ),
            "examples": [
                "thin (neutral) / slim (positive) / skinny (negative)",
                "cheap (can be negative) / inexpensive (neutral)",
                "childish (negative) / childlike (positive)",
                "He is determined, not just stubborn.",
            ],
            "practice": [
                {"question": "A positive word for 'thin' (a person).", "answer": "slim"},
                {"question": "A neutral word for 'cheap'.", "answer": "inexpensive"},
                {"question": "A positive version of 'childish'.", "answer": "childlike"},
            ],
        },
    ],
    "C2": [
        {
            "type": "grammar",
            "title": "Cleft Sentences for Focus",
            "explanation": (
                "Cleft sentences split one idea into two clauses to emphasise a particular part. "
                "Use 'It is/was ... that ...' and 'What ... is ...'. They give precise, controlled "
                "emphasis in sophisticated discourse."
            ),
            "examples": [
                "It was her honesty that impressed me.",
                "What I need is a clear plan.",
                "It is the small details that matter most.",
                "What surprised everyone was his calm.",
            ],
            "practice": [
                {"question": "Emphasise 'the music': 'The music ruined the evening.'", "answer": "It was the music that ruined the evening."},
                {"question": "Use 'What ...': 'I want some peace.'", "answer": "What I want is some peace."},
                {"question": "Emphasise 'his attitude': 'His attitude annoyed them.'", "answer": "It was his attitude that annoyed them."},
            ],
        },
        {
            "type": "grammar",
            "title": "Subjunctive and Unreal Forms",
            "explanation": (
                "The subjunctive appears after verbs of suggestion/demand (insist, recommend, "
                "require) using the base verb, and in fixed expressions. It is a marker of formal, "
                "polished English."
            ),
            "examples": [
                "I insist that he be present.",
                "The board recommended that she resign.",
                "It is essential that every word be checked.",
                "If I were you, I would reconsider.",
            ],
            "practice": [
                {"question": "'The doctor recommended that he ___ (rest).'", "answer": "rest"},
                {"question": "'It is vital that she ___ (be) informed.'", "answer": "be"},
                {"question": "'They demanded that the rule ___ (change).'", "answer": "change"},
            ],
        },
        {
            "type": "grammar",
            "title": "Discourse Markers and Cohesion",
            "explanation": (
                "Advanced writers signpost their argument with precise discourse markers that "
                "show contrast, concession, consequence, and reformulation. Used well, they make "
                "complex texts flow seamlessly."
            ),
            "examples": [
                "Notwithstanding the objections, the thesis holds.",
                "Granted, the data is limited; nevertheless, the trend is clear.",
                "In other words, the policy backfired.",
                "By the same token, the reverse is also true.",
            ],
            "practice": [
                {"question": "A formal marker meaning 'in spite of'.", "answer": "notwithstanding"},
                {"question": "A marker that concedes a point ('it is true that').", "answer": "granted / admittedly"},
                {"question": "A marker introducing a restatement.", "answer": "in other words"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Idiomatic Mastery and Register Shift",
            "explanation": (
                "At C2 you move effortlessly between formal and colloquial registers and deploy "
                "idioms with precision. The skill is matching the expression to the exact tone "
                "of the situation."
            ),
            "examples": [
                "to throw caution to the wind (= take a risk)",
                "a sweeping generalisation (formal critique)",
                "to play devil's advocate (argue the opposite to test an idea)",
                "That is, if I may, a moot point.",
            ],
            "practice": [
                {"question": "An idiom meaning 'to take a big risk'.", "answer": "to throw caution to the wind"},
                {"question": "Arguing against an idea just to test it is to play ___.", "answer": "devil's advocate"},
                {"question": "A point no longer worth debating is a ___ point.", "answer": "moot"},
            ],
        },
        {
            "type": "vocabulary",
            "title": "Connotation, Irony and Tone",
            "explanation": (
                "Mastery means reading and producing subtle tone — irony, understatement, and "
                "loaded connotation — so meaning works on more than one level."
            ),
            "examples": [
                "understatement: 'It's a bit chilly' (in freezing weather)",
                "irony: 'What a lovely surprise,' she said flatly.",
                "loaded: 'regime' vs neutral 'government'",
                "The irony was not lost on me.",
            ],
            "practice": [
                {"question": "Saying less than you mean for effect is called ___.", "answer": "understatement"},
                {"question": "'Regime' has a more negative ___ than 'government'.", "answer": "connotation"},
                {"question": "Meaning the opposite of the literal words is ___.", "answer": "irony"},
            ],
        },
    ],
}

_GEN_SYSTEM = (
    "You are a CEFR English teacher who creates short, self-contained TEACHING lessons. "
    "For the given level, output 5 lessons (3 grammar + 2 vocabulary). Each lesson must "
    "TEACH a single point in clear, simple English appropriate to the level: a short title, "
    "an explanation a learner at that level can understand, 3-4 short example sentences, and "
    "a tiny practice of 3 question/answer items. "
    'Return ONLY JSON: {"lessons": [{"type": "grammar" or "vocabulary", "title": string, '
    '"explanation": string, "examples": [string], "practice": [{"question": string, '
    '"answer": string}]}]}'
)

# Cache generated lessons per level (regenerate after TTL). In-memory; swap for Redis at scale.
_CACHE_TTL = 60 * 60 * 24
_cache: dict[str, tuple[float, list[dict]]] = {}


def _stable_id(level: str, lesson_type: str, index: int) -> str:
    return f"{level}-{lesson_type}-{index + 1}"


def _with_ids(level: str, items: list[dict]) -> list[dict]:
    """Attach stable, deterministic ids per (level, type) and normalise shape."""
    counters = {t: 0 for t in TYPES}
    out: list[dict] = []
    for item in items:
        lesson_type = item.get("type") if item.get("type") in TYPES else "grammar"
        index = counters[lesson_type]
        counters[lesson_type] += 1
        examples = [str(e).strip() for e in (item.get("examples") or []) if str(e).strip()]
        practice = []
        for p in item.get("practice") or []:
            if not isinstance(p, dict):
                continue
            question = str(p.get("question") or "").strip()
            answer = str(p.get("answer") or "").strip()
            if question and answer:
                practice.append({"question": question, "answer": answer})
        out.append(
            {
                "id": _stable_id(level, lesson_type, index),
                "level": level,
                "type": lesson_type,
                "title": str(item.get("title") or "").strip() or "Lesson",
                "explanation": str(item.get("explanation") or "").strip(),
                "examples": examples,
                "practice": practice,
            }
        )
    return out


def _curated(level: str) -> list[dict]:
    items = CURATED_LESSONS.get(level, CURATED_LESSONS["A1"])
    return _with_ids(level, items)


def _parse(raw: str) -> list[dict] | None:
    text = (raw or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    s, e = text.find("{"), text.rfind("}")
    if s == -1 or e == -1:
        return None
    try:
        data = json.loads(text[s : e + 1])
    except json.JSONDecodeError:
        return None
    lessons = data.get("lessons")
    if not isinstance(lessons, list) or not lessons:
        return None
    # Keep only entries that look like real, teachable lessons.
    valid = [
        item
        for item in lessons
        if isinstance(item, dict)
        and str(item.get("title") or "").strip()
        and str(item.get("explanation") or "").strip()
    ]
    return valid or None


async def get_level_lessons(level: str) -> list[dict]:
    """Auto-generated (cached) teaching lessons for a level; curated fallback on any failure."""
    level = (level or "A1").upper()
    if level not in CURATED_LESSONS:
        level = "A1"

    cached = _cache.get(level)
    if cached and cached[0] > time.time():
        return cached[1]

    if is_claude_configured():
        try:
            from app.services.language_conversation_prompts import level_calibration_line

            raw = await generate_llm_json(
                f"Create the {level} grammar & vocabulary teaching lessons now." + level_calibration_line(level),
                system=_GEN_SYSTEM,
                temperature=0.4,
                max_output_tokens=8192,
            )
            parsed = _parse(raw)
            if parsed:
                out = _with_ids(level, parsed[:6])
                if out:
                    _cache[level] = (time.time() + _CACHE_TTL, out)
                    return out
        except Exception as exc:
            logger.warning("Lessons AI generation failed for %s: %s", level, exc)

    curated = _curated(level)
    _cache[level] = (time.time() + _CACHE_TTL, curated)
    return curated


async def _current_level(db: AsyncSession, *, student_id: int, language_id: int) -> str:
    """Resolve the student's working level — same approach as the curriculum service."""
    analytics = await db.get(LanguageAnalytics, {"student_id": student_id, "language_id": language_id})
    level: LanguageLevel | None = None
    if analytics:
        level = analytics.overall_level_internal or bottleneck_level(
            {
                "reading": analytics.reading_level.value if analytics.reading_level else None,
                "listening": analytics.listening_level.value if analytics.listening_level else None,
                "writing": analytics.writing_level.value if analytics.writing_level else None,
                "speaking": analytics.speaking_level.value if analytics.speaking_level else None,
            }
        )
    return level.value if level else "A1"


async def list_lessons(db: AsyncSession, *, student_id: int) -> dict:
    """Lessons for the student's current level, each with a stable id."""
    language = await get_default_language(db)
    level = await _current_level(db, student_id=student_id, language_id=language.id)
    lessons = await get_level_lessons(level)
    return {"level": level, "lessons": lessons}


async def get_lesson(db: AsyncSession, *, student_id: int, lesson_id: str) -> dict | None:
    """Find a single lesson by id within the student's level set."""
    payload = await list_lessons(db, student_id=student_id)
    for lesson in payload["lessons"]:
        if lesson["id"] == lesson_id:
            return lesson
    return None
