-- Official language progression storage (Phase 4.2.1).
-- Authoritative Official CEFR; no runtime readers switched in this migration.

CREATE TABLE IF NOT EXISTS public.language_progression (
    student_id integer NOT NULL,
    language_id integer NOT NULL,
    official_reading_cefr public.language_level DEFAULT 'A1'::public.language_level NOT NULL,
    official_listening_cefr public.language_level DEFAULT 'A1'::public.language_level NOT NULL,
    official_writing_cefr public.language_level DEFAULT 'A1'::public.language_level NOT NULL,
    official_speaking_cefr public.language_level DEFAULT 'A1'::public.language_level NOT NULL,
    official_overall_cefr public.language_level DEFAULT 'A1'::public.language_level NOT NULL,
    learning_stage_reading smallint DEFAULT 1 NOT NULL,
    learning_stage_listening smallint DEFAULT 1 NOT NULL,
    learning_stage_writing smallint DEFAULT 1 NOT NULL,
    learning_stage_speaking smallint DEFAULT 1 NOT NULL,
    promotion_readiness_score smallint DEFAULT 0 NOT NULL,
    promotion_readiness_json jsonb,
    promotion_cooldown_until timestamp with time zone,
    last_promotion_at timestamp with time zone,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT language_progression_pkey PRIMARY KEY (student_id, language_id),
    CONSTRAINT language_progression_student_id_fkey
        FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT language_progression_language_id_fkey
        FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_language_progression_official_overall_cefr
    ON public.language_progression (official_overall_cefr);

CREATE TABLE IF NOT EXISTS public.language_progression_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    language_id integer NOT NULL,
    event_type character varying(64) NOT NULL,
    payload_json jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT language_progression_events_student_id_fkey
        FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT language_progression_events_language_id_fkey
        FOREIGN KEY (language_id) REFERENCES public.languages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_language_progression_events_student_id
    ON public.language_progression_events (student_id);

CREATE INDEX IF NOT EXISTS ix_language_progression_events_language_id
    ON public.language_progression_events (language_id);

CREATE INDEX IF NOT EXISTS ix_language_progression_events_created_at
    ON public.language_progression_events (created_at DESC);
