"""English Grammar Catalog v1 — legacy Python authoring seed (S12).

Production catalog SSOT is ``backend/curriculum/english/grammar/*.yaml``,
loaded by ``language_grammar_catalog.loader``. This module remains only as a
seed/export helper for curriculum generation scripts — not the runtime authority.
"""

from __future__ import annotations

from app.services.language_grammar.enums import GrammarCEFRBand as C
from app.services.language_grammar_catalog.builder import R, derive_future_edges, ev, topic
from app.services.language_grammar_catalog.types import GrammarTopic

CATALOG_LANGUAGE_CODE = "en"
CATALOG_ID = "english_grammar_v1"


def _raw_topics() -> tuple[GrammarTopic, ...]:
    """Author prerequisite edges only; future edges are derived."""
    return (
        # ── A1 ──────────────────────────────────────────────────────────
        topic(
            "gram_be_present",
            display_name="Present of be",
            cefr_band=C.A1,
            introduction_order=10,
            learning_objectives=(
                "Use am/is/are for identity, location, and basic description",
                "Form simple negative and question forms with be",
            ),
            demonstration_patterns=("am", "is", "are", "isn't", "aren't"),
            example_sentences=(
                "I am a student.",
                "She is at school.",
                "They are not ready.",
            ),
            common_errors=(
                "He are tired.",
                "I is happy.",
                "Omitting be: She my friend.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("classroom introductions", "family description"),
            minimum_context_diversity=2,
            evidence_requirements=ev(min_observations=3, min_skills_covered=1),
            mastery_threshold=75.0,
            review_priority=4,
            review_half_life_days=10.0,
            focus_note="Foundation for almost every later structure.",
        ),
        topic(
            "gram_personal_pronouns",
            display_name="Personal pronouns",
            cefr_band=C.A1,
            introduction_order=20,
            prerequisite_ids=("gram_be_present",),
            learning_objectives=(
                "Use subject pronouns correctly",
                "Match pronouns to be and simple verbs",
            ),
            demonstration_patterns=("I", "you", "he", "she", "it", "we", "they"),
            example_sentences=(
                "He is my brother.",
                "We are friends.",
                "It is a book.",
            ),
            common_errors=(
                "Him is my friend.",
                "She name is Sara.",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("introducing people", "pointing to objects"),
            mastery_threshold=75.0,
            review_priority=3,
            focus_note="Keep forms short and high-frequency.",
        ),
        topic(
            "gram_present_simple",
            display_name="Present simple",
            cefr_band=C.A1,
            introduction_order=30,
            prerequisite_ids=("gram_be_present", "gram_personal_pronouns"),
            learning_objectives=(
                "Express habits and facts with present simple",
                "Use third-person -s where required",
            ),
            demonstration_patterns=("is", "are", "want", "need", "says", "live", "like"),
            example_sentences=(
                "I live in Damascus.",
                "She wants a ticket.",
                "They need help.",
            ),
            common_errors=(
                "She want a ticket.",
                "He don't like coffee.",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("daily routines", "city facts", "preferences"),
            evidence_requirements=ev(min_observations=4, min_distinct_contexts=2, min_skills_covered=2),
            mastery_threshold=78.0,
            review_priority=5,
            review_half_life_days=12.0,
            focus_note="Show simple present facts and habits (no lecture).",
        ),
        topic(
            "gram_articles_a_an_the",
            display_name="Articles a / an / the",
            cefr_band=C.A1,
            introduction_order=40,
            prerequisite_ids=("gram_be_present",),
            learning_objectives=(
                "Choose a/an for singular countable nouns",
                "Use the for known/specific references at A1",
            ),
            demonstration_patterns=("a", "an", "the"),
            example_sentences=(
                "I have a book.",
                "She eats an apple.",
                "The door is open.",
            ),
            common_errors=(
                "I have book.",
                "She eats a apple.",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("classroom objects", "shopping list"),
            mastery_threshold=75.0,
            review_priority=3,
            focus_note="Keep article rules light; accuracy over metalanguage.",
        ),
        topic(
            "gram_there_is_are",
            display_name="There is / there are",
            cefr_band=C.A1,
            introduction_order=50,
            prerequisite_ids=("gram_be_present", "gram_articles_a_an_the"),
            learning_objectives=(
                "Describe existence and quantity with there is/are",
            ),
            demonstration_patterns=("there is", "there are", "there isn't", "there aren't"),
            example_sentences=(
                "There is a park near my house.",
                "There are three chairs.",
            ),
            common_errors=(
                "There have a park.",
                "There is three chairs.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("describing a room", "map landmarks"),
            mastery_threshold=75.0,
            review_priority=3,
        ),
        topic(
            "gram_basic_questions",
            display_name="Basic questions",
            cefr_band=C.A1,
            introduction_order=60,
            prerequisite_ids=("gram_present_simple",),
            learning_objectives=(
                "Form yes/no and Wh- questions for basic information",
                "Answer questions with short, accurate replies",
            ),
            demonstration_patterns=("what", "where", "who", "can you", "do you", "?"),
            example_sentences=(
                "Where do you live?",
                "What is your name?",
                "Can you help me?",
            ),
            common_errors=(
                "Where you live?",
                "What you name?",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("meeting someone new", "asking for directions"),
            evidence_requirements=ev(min_observations=4, min_skills_covered=2),
            mastery_threshold=78.0,
            review_priority=5,
            focus_note="Include simple spoken questions characters ask each other.",
        ),
        topic(
            "gram_can_ability",
            display_name="Can for ability / permission",
            cefr_band=C.A1,
            introduction_order=70,
            prerequisite_ids=("gram_present_simple", "gram_basic_questions"),
            learning_objectives=(
                "Express ability and simple permission with can/can't",
            ),
            demonstration_patterns=("can", "can't", "cannot"),
            example_sentences=(
                "I can swim.",
                "Can I open the window?",
                "She can't drive.",
            ),
            common_errors=(
                "I can to swim.",
                "She cans drive.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("skills interview", "classroom permission"),
            mastery_threshold=76.0,
            review_priority=3,
        ),
        topic(
            "gram_possessives",
            display_name="Possessives",
            cefr_band=C.A1,
            introduction_order=80,
            prerequisite_ids=("gram_personal_pronouns", "gram_articles_a_an_the"),
            learning_objectives=(
                "Use possessive adjectives and 's for ownership",
            ),
            demonstration_patterns=("my", "your", "his", "her", "our", "their", "'s"),
            example_sentences=(
                "This is my bag.",
                "Sara's phone is new.",
            ),
            common_errors=(
                "This is me bag.",
                "The phone of Sara is new. (overused at A1)",
            ),
            best_reinforcement_skills=(R.writing, R.speaking),
            recommended_contexts=("family belongings", "classroom objects"),
            mastery_threshold=75.0,
            review_priority=2,
        ),
        # ── A2 ──────────────────────────────────────────────────────────
        topic(
            "gram_present_continuous",
            display_name="Present continuous",
            cefr_band=C.A2,
            introduction_order=110,
            prerequisite_ids=("gram_be_present", "gram_present_simple"),
            learning_objectives=(
                "Describe actions happening now with be + -ing",
                "Contrast temporary vs habitual meaning lightly",
            ),
            demonstration_patterns=("am -ing", "is -ing", "are -ing"),
            example_sentences=(
                "I am waiting for the bus.",
                "They are studying English.",
            ),
            common_errors=(
                "I waiting for the bus.",
                "She is study now.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("what is happening now", "phone call updates"),
            mastery_threshold=78.0,
            review_priority=4,
        ),
        topic(
            "gram_past_simple",
            display_name="Past simple",
            cefr_band=C.A2,
            introduction_order=120,
            prerequisite_ids=("gram_present_simple",),
            learning_objectives=(
                "Narrate finished past actions with regular/irregular verbs",
                "Form past negatives and questions with did",
            ),
            demonstration_patterns=("arrived", "missed", "said", "was", "were", "did", "didn't"),
            example_sentences=(
                "I arrived late yesterday.",
                "She didn't see the message.",
                "Where did you go?",
            ),
            common_errors=(
                "I did went home.",
                "She not see the message.",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("yesterday's problem", "travel story"),
            evidence_requirements=ev(min_observations=4, min_distinct_contexts=2, min_skills_covered=2),
            mastery_threshold=80.0,
            review_priority=5,
            review_half_life_days=14.0,
            focus_note="Show finished actions that created today's problem.",
        ),
        topic(
            "gram_connectors_and_but",
            display_name="Simple connectors",
            cefr_band=C.A2,
            introduction_order=130,
            prerequisite_ids=("gram_present_simple",),
            learning_objectives=(
                "Link ideas with and / but / because",
            ),
            demonstration_patterns=("and", "but", "because"),
            example_sentences=(
                "I was tired but I finished the work.",
                "She stayed home because it was raining.",
            ),
            common_errors=(
                "Because it was raining. (sentence fragment)",
                "I tired but I finished.",
            ),
            best_reinforcement_skills=(R.writing, R.speaking),
            recommended_contexts=("explaining a choice", "short narrative"),
            mastery_threshold=78.0,
            review_priority=3,
            focus_note="Link ideas with and / but / because inside the case.",
        ),
        topic(
            "gram_comparatives_basic",
            display_name="Comparatives and superlatives (basic)",
            cefr_band=C.A2,
            introduction_order=140,
            prerequisite_ids=("gram_present_simple", "gram_articles_a_an_the"),
            learning_objectives=(
                "Compare people/things with -er / more and the -est / most",
            ),
            demonstration_patterns=("bigger", "more interesting", "the best", "than"),
            example_sentences=(
                "This bag is bigger than that one.",
                "English is more useful for my job.",
            ),
            common_errors=(
                "more bigger",
                "the most tallest",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("choosing a product", "comparing cities"),
            mastery_threshold=78.0,
            review_priority=3,
        ),
        topic(
            "gram_going_to",
            display_name="Going to future",
            cefr_band=C.A2,
            introduction_order=150,
            prerequisite_ids=("gram_present_continuous", "gram_present_simple"),
            learning_objectives=(
                "Express plans and intentions with going to",
                "Contrast lightly with will for spontaneous decisions",
            ),
            demonstration_patterns=("going to", "will"),
            example_sentences=(
                "I am going to call the teacher.",
                "We are going to visit the museum tomorrow.",
            ),
            common_errors=(
                "I going to call the teacher.",
                "I will to visit the museum.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("weekend plans", "open ending next step"),
            mastery_threshold=80.0,
            review_priority=4,
            focus_note="Show a planned next step inside the open ending.",
        ),
        topic(
            "gram_countable_uncountable",
            display_name="Countable and uncountable nouns",
            cefr_band=C.A2,
            introduction_order=160,
            prerequisite_ids=("gram_articles_a_an_the", "gram_there_is_are"),
            learning_objectives=(
                "Use some/any/much/many with countable and uncountable nouns",
            ),
            demonstration_patterns=("some", "any", "much", "many", "a lot of"),
            example_sentences=(
                "I need some water.",
                "How many books do you have?",
            ),
            common_errors=(
                "How many water?",
                "I need a water.",
            ),
            best_reinforcement_skills=(R.writing, R.listening),
            recommended_contexts=("shopping", "kitchen inventory"),
            mastery_threshold=78.0,
            review_priority=3,
        ),
        topic(
            "gram_modals_should_must",
            display_name="Should / must (advice and obligation)",
            cefr_band=C.A2,
            introduction_order=170,
            prerequisite_ids=("gram_can_ability",),
            learning_objectives=(
                "Give advice with should and strong obligation with must",
            ),
            demonstration_patterns=("should", "shouldn't", "must", "mustn't"),
            example_sentences=(
                "You should rest.",
                "Students must arrive on time.",
            ),
            common_errors=(
                "You should to rest.",
                "You must to arrive.",
            ),
            best_reinforcement_skills=(R.speaking, R.reading),
            recommended_contexts=("school rules", "health advice"),
            mastery_threshold=78.0,
            review_priority=3,
        ),
        topic(
            "gram_past_continuous",
            display_name="Past continuous",
            cefr_band=C.A2,
            introduction_order=180,
            prerequisite_ids=("gram_past_simple", "gram_present_continuous"),
            learning_objectives=(
                "Describe interrupted or background past actions",
            ),
            demonstration_patterns=("was -ing", "were -ing", "when", "while"),
            example_sentences=(
                "I was walking when it started to rain.",
                "They were studying while we cooked.",
            ),
            common_errors=(
                "I walking when it started.",
                "I was walk when...",
            ),
            best_reinforcement_skills=(R.listening, R.speaking),
            recommended_contexts=("what happened yesterday", "story interruption"),
            mastery_threshold=80.0,
            review_priority=3,
        ),
        # ── B1 ──────────────────────────────────────────────────────────
        topic(
            "gram_present_perfect",
            display_name="Present perfect",
            cefr_band=C.B1,
            introduction_order=210,
            prerequisite_ids=("gram_past_simple", "gram_present_simple"),
            learning_objectives=(
                "Connect past experience/result to the present",
                "Use already / yet / just / ever / never appropriately",
            ),
            demonstration_patterns=("have", "has", "already", "yet", "just", "ever", "never"),
            example_sentences=(
                "I have already finished the task.",
                "Have you ever visited Aleppo?",
                "She hasn't replied yet.",
            ),
            common_errors=(
                "I have finished yesterday.",
                "Did you ever visited Aleppo?",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("life experience", "present consequence of past action"),
            evidence_requirements=ev(min_observations=5, min_distinct_contexts=3, min_skills_covered=2),
            mastery_threshold=82.0,
            review_priority=5,
            review_half_life_days=16.0,
            focus_note="Connect past actions to a present consequence in the case.",
        ),
        topic(
            "gram_first_conditional",
            display_name="First conditional",
            cefr_band=C.B1,
            introduction_order=220,
            prerequisite_ids=("gram_present_simple", "gram_going_to"),
            learning_objectives=(
                "Express real future conditions with if + present, will/might",
            ),
            demonstration_patterns=("if", "will", "might", "unless"),
            example_sentences=(
                "If it rains, we will stay inside.",
                "If you study, you might pass.",
            ),
            common_errors=(
                "If it will rain, we will stay inside.",
                "If you will study, you pass.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("planning under conditions", "cause/effect choices"),
            evidence_requirements=ev(min_observations=4, min_distinct_contexts=2, min_skills_covered=2),
            mastery_threshold=82.0,
            review_priority=4,
            focus_note="Show cause/effect choices characters consider.",
        ),
        topic(
            "gram_reported_speech_light",
            display_name="Reported situation",
            cefr_band=C.B1,
            introduction_order=230,
            prerequisite_ids=("gram_past_simple", "gram_present_simple"),
            learning_objectives=(
                "Report what someone said without heavy backshift lectures",
            ),
            demonstration_patterns=("said that", "told", "asked"),
            example_sentences=(
                "She said that the meeting was cancelled.",
                "He told me to wait.",
            ),
            common_errors=(
                "He said me to wait.",
                "She told that the meeting was cancelled.",
            ),
            best_reinforcement_skills=(R.listening, R.speaking),
            recommended_contexts=("relaying a message", "school announcement"),
            mastery_threshold=80.0,
            review_priority=3,
            focus_note="Report what someone said without becoming a grammar lecture.",
        ),
        topic(
            "gram_used_to",
            display_name="Used to (past habits)",
            cefr_band=C.B1,
            introduction_order=240,
            prerequisite_ids=("gram_past_simple",),
            learning_objectives=(
                "Contrast past habits with present using used to",
            ),
            demonstration_patterns=("used to", "didn't use to"),
            example_sentences=(
                "I used to walk to school.",
                "She didn't use to like coffee.",
            ),
            common_errors=(
                "I use to walk to school.",
                "I didn't used to like coffee.",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("childhood habits", "life changes"),
            mastery_threshold=80.0,
            review_priority=3,
        ),
        topic(
            "gram_relative_clauses_basic",
            display_name="Defining relative clauses (basic)",
            cefr_band=C.B1,
            introduction_order=250,
            prerequisite_ids=("gram_present_simple", "gram_connectors_and_but"),
            learning_objectives=(
                "Add essential information with who/which/that",
            ),
            demonstration_patterns=("who", "which", "that"),
            example_sentences=(
                "The student who called you is waiting.",
                "This is the book that I need.",
            ),
            common_errors=(
                "The student which called you...",
                "The book what I need...",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("identifying people", "defining objects"),
            mastery_threshold=80.0,
            review_priority=3,
        ),
        topic(
            "gram_modals_possibility",
            display_name="Modals of possibility (may / might / could)",
            cefr_band=C.B1,
            introduction_order=260,
            prerequisite_ids=("gram_modals_should_must", "gram_first_conditional"),
            learning_objectives=(
                "Express uncertainty and possibility with may/might/could",
            ),
            demonstration_patterns=("may", "might", "could"),
            example_sentences=(
                "It might rain later.",
                "She could be at home.",
            ),
            common_errors=(
                "It can rain later. (wrong certainty for prediction)",
                "She might to be at home.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("uncertain plans", "guessing reasons"),
            mastery_threshold=80.0,
            review_priority=3,
        ),
        # ── B2 ──────────────────────────────────────────────────────────
        topic(
            "gram_second_conditional",
            display_name="Second conditional",
            cefr_band=C.B2,
            introduction_order=310,
            prerequisite_ids=("gram_first_conditional", "gram_past_simple"),
            learning_objectives=(
                "Express unreal/hypothetical present-future conditions",
            ),
            demonstration_patterns=("if", "would", "could", "were"),
            example_sentences=(
                "If I had more time, I would travel.",
                "If she were here, she could help.",
            ),
            common_errors=(
                "If I would have more time, I would travel.",
                "If she was here... (acceptable variation; teach were for formality)",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("ethical dilemmas", "hypothetical advice"),
            mastery_threshold=84.0,
            review_priority=4,
        ),
        topic(
            "gram_mixed_conditionals_light",
            display_name="Hypothetical / unreal conditional",
            cefr_band=C.B2,
            introduction_order=320,
            prerequisite_ids=("gram_second_conditional", "gram_present_perfect"),
            learning_objectives=(
                "Handle light mixed/unreal conditionals for consequence reasoning",
            ),
            demonstration_patterns=("would", "could", "if only", "unless"),
            example_sentences=(
                "If only we had left earlier, we would be there now.",
                "Unless we act, the problem will grow.",
            ),
            common_errors=(
                "If only we would left earlier...",
                "Unless we will act...",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("ethical consequences", "regret scenarios"),
            evidence_requirements=ev(min_observations=5, min_distinct_contexts=3, min_skills_covered=2),
            mastery_threshold=85.0,
            review_priority=4,
            focus_note="Show unreal or ethical consequences characters weigh.",
        ),
        topic(
            "gram_passive_voice",
            display_name="Passive voice",
            cefr_band=C.B2,
            introduction_order=330,
            prerequisite_ids=("gram_past_simple", "gram_present_perfect"),
            learning_objectives=(
                "Form passives to focus on outcomes and unknown agents",
                "Use present/past/perfect passive forms appropriately",
            ),
            demonstration_patterns=("was told", "is expected", "were given", "has been"),
            example_sentences=(
                "The students were given clear instructions.",
                "The decision has been delayed.",
            ),
            common_errors=(
                "The students was given...",
                "The decision has delayed.",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("news headline", "school notice", "institutional outcome"),
            minimum_context_diversity=3,
            evidence_requirements=ev(min_observations=5, min_distinct_contexts=3, min_skills_covered=2),
            mastery_threshold=85.0,
            review_priority=5,
            review_half_life_days=18.0,
            focus_note="Show outcomes affected by unknown or institutional agents.",
        ),
        topic(
            "gram_relative_clauses",
            display_name="Relative clauses",
            cefr_band=C.B2,
            introduction_order=340,
            prerequisite_ids=("gram_relative_clauses_basic",),
            learning_objectives=(
                "Embed non-defining and richer defining relative detail",
            ),
            demonstration_patterns=(" who ", " which ", " that ", "whose", "where"),
            example_sentences=(
                "The manager, who arrived late, apologised.",
                "This is the policy that changed everything.",
            ),
            common_errors=(
                "The manager which arrived late...",
                "Comma misuse with defining clauses",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("people and decisions", "formal description"),
            mastery_threshold=84.0,
            review_priority=4,
            focus_note="Embed detail about people/decisions with who/which/that.",
        ),
        topic(
            "gram_reported_questions",
            display_name="Reported questions",
            cefr_band=C.B2,
            introduction_order=350,
            prerequisite_ids=("gram_reported_speech_light", "gram_basic_questions"),
            learning_objectives=(
                "Report yes/no and Wh- questions with statement word order",
            ),
            demonstration_patterns=("asked if", "asked whether", "asked what", "wondered"),
            example_sentences=(
                "She asked if I was ready.",
                "He asked where the office was.",
            ),
            common_errors=(
                "She asked if was I ready.",
                "He asked where was the office.",
            ),
            best_reinforcement_skills=(R.listening, R.speaking),
            recommended_contexts=("interview retell", "customer service report"),
            mastery_threshold=84.0,
            review_priority=3,
        ),
        topic(
            "gram_causatives_basic",
            display_name="Have/get something done",
            cefr_band=C.B2,
            introduction_order=360,
            prerequisite_ids=("gram_passive_voice",),
            learning_objectives=(
                "Express arranged services with have/get + object + past participle",
            ),
            demonstration_patterns=("have ... done", "get ... done"),
            example_sentences=(
                "I had my phone repaired.",
                "She got her essay checked.",
            ),
            common_errors=(
                "I had repaired my phone.",
                "She got check her essay.",
            ),
            best_reinforcement_skills=(R.speaking, R.writing),
            recommended_contexts=("services", "arranging help"),
            mastery_threshold=84.0,
            review_priority=2,
        ),
        # ── C1 ──────────────────────────────────────────────────────────
        topic(
            "gram_advanced_modals",
            display_name="Advanced modality",
            cefr_band=C.C1,
            introduction_order=410,
            prerequisite_ids=("gram_modals_possibility", "gram_present_perfect"),
            learning_objectives=(
                "Express obligation, speculation, and moral pressure with perfect modals",
            ),
            demonstration_patterns=("must have", "should have", "might have", "ought to"),
            example_sentences=(
                "They must have missed the announcement.",
                "You should have told me earlier.",
            ),
            common_errors=(
                "They must missed the announcement.",
                "You should had told me.",
            ),
            best_reinforcement_skills=(R.speaking, R.listening),
            recommended_contexts=("speculation about past", "moral pressure"),
            evidence_requirements=ev(min_observations=5, min_distinct_contexts=3, min_skills_covered=2),
            mastery_threshold=88.0,
            review_priority=4,
            review_half_life_days=20.0,
            focus_note="Show obligation, speculation, and moral pressure with modals.",
        ),
        topic(
            "gram_cleft_emphasis",
            display_name="Emphasis / clefting",
            cefr_band=C.C1,
            introduction_order=420,
            prerequisite_ids=("gram_relative_clauses", "gram_present_simple"),
            learning_objectives=(
                "Emphasize contested facts with it-clefts and wh-clefts",
            ),
            demonstration_patterns=("it is", "what matters", "the fact that"),
            example_sentences=(
                "It is the process that failed, not the people.",
                "What matters is clear evidence.",
            ),
            common_errors=(
                "It is the process which failed are...",
                "What matters are clear evidence.",
            ),
            best_reinforcement_skills=(R.writing, R.speaking),
            recommended_contexts=("debate stance", "responsibility focus"),
            mastery_threshold=88.0,
            review_priority=3,
            focus_note="Emphasize a contested fact or responsibility.",
        ),
        topic(
            "gram_concession",
            display_name="Concession and contrast",
            cefr_band=C.C1,
            introduction_order=430,
            prerequisite_ids=("gram_connectors_and_but", "gram_relative_clauses"),
            learning_objectives=(
                "Hold conflicting views with although / even though / whereas / despite",
            ),
            demonstration_patterns=("although", "even though", "whereas", "despite"),
            example_sentences=(
                "Although the plan was risky, they approved it.",
                "Despite the delay, the team finished.",
            ),
            common_errors=(
                "Despite of the delay...",
                "Although they approved it but...",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("balanced argument", "conflicting stakeholder views"),
            mastery_threshold=88.0,
            review_priority=4,
            focus_note="Hold conflicting views in the same situation.",
        ),
        topic(
            "gram_inversion_emphasis",
            display_name="Negative inversion for emphasis",
            cefr_band=C.C1,
            introduction_order=440,
            prerequisite_ids=("gram_cleft_emphasis", "gram_advanced_modals"),
            learning_objectives=(
                "Use limited negative inversion for formal emphasis",
            ),
            demonstration_patterns=("never have I", "not only", "rarely does"),
            example_sentences=(
                "Never have I seen such confusion.",
                "Not only did she finish early, she also helped others.",
            ),
            common_errors=(
                "Never I have seen...",
                "Not only she finished early...",
            ),
            best_reinforcement_skills=(R.writing, R.reading),
            recommended_contexts=("formal speech", "persuasive essay"),
            mastery_threshold=90.0,
            review_priority=2,
            review_half_life_days=21.0,
        ),
        # ── C2 ──────────────────────────────────────────────────────────
        topic(
            "gram_nominalisation",
            display_name="Nominalisation",
            cefr_band=C.C2,
            introduction_order=510,
            prerequisite_ids=("gram_passive_voice", "gram_concession"),
            learning_objectives=(
                "Convert processes into noun phrases for academic/formal density",
            ),
            demonstration_patterns=("the implementation of", "a failure to", "the decision to"),
            example_sentences=(
                "The implementation of the policy reduced delays.",
                "Their failure to respond weakened trust.",
            ),
            common_errors=(
                "Over-nominalising spoken turns",
                "Awkward of-chains without clear agents",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("academic summary", "policy brief"),
            minimum_context_diversity=3,
            evidence_requirements=ev(min_observations=5, min_distinct_contexts=3, min_skills_covered=2),
            mastery_threshold=90.0,
            review_priority=3,
            review_half_life_days=24.0,
        ),
        topic(
            "gram_hedging_stance",
            display_name="Hedging and stance",
            cefr_band=C.C2,
            introduction_order=520,
            prerequisite_ids=("gram_advanced_modals", "gram_cleft_emphasis"),
            learning_objectives=(
                "Softened claims and precise stance markers in academic/professional discourse",
            ),
            demonstration_patterns=("appears to", "it seems that", "arguably", "to some extent"),
            example_sentences=(
                "The data appears to support the claim.",
                "Arguably, the delay was avoidable.",
            ),
            common_errors=(
                "Over-hedging that removes commitment",
                "Mixing absolute claims with hedges incoherently",
            ),
            best_reinforcement_skills=(R.writing, R.speaking),
            recommended_contexts=("research discussion", "diplomatic disagreement"),
            mastery_threshold=90.0,
            review_priority=3,
            review_half_life_days=24.0,
        ),
        topic(
            "gram_discourse_signalling",
            display_name="Advanced discourse signalling",
            cefr_band=C.C2,
            introduction_order=530,
            prerequisite_ids=("gram_concession", "gram_inversion_emphasis"),
            learning_objectives=(
                "Signal contrast, consequence, and reframing with advanced discourse markers",
            ),
            demonstration_patterns=("nevertheless", "thereby", "insofar as", "conversely"),
            example_sentences=(
                "The plan failed; nevertheless, the process improved.",
                "Conversely, delaying action increased risk.",
            ),
            common_errors=(
                "Using advanced markers without logical fit",
                "Stacking markers that obscure meaning",
            ),
            best_reinforcement_skills=(R.reading, R.writing),
            recommended_contexts=("editorial argument", "policy rebuttal"),
            mastery_threshold=92.0,
            review_priority=2,
            review_half_life_days=28.0,
        ),
    )


def build_english_grammar_topics() -> tuple[GrammarTopic, ...]:
    """Deprecated seed builder — prefer YAML curriculum via get_english_catalog()."""
    raw = _raw_topics()
    ordered = tuple(sorted(raw, key=lambda t: (t.introduction_order, t.grammar_id)))
    return derive_future_edges(ordered)
