"""v1 Speaking Skill Dependency Graph catalog (S1).

Stable skill IDs use ``category:slug`` format — never derived from display labels.
"""

from __future__ import annotations

from app.services.language_speaking.enums import OfficialSpeakingCEFR as C
from app.services.language_speaking.enums import SpeakingGoal as G
from app.services.language_speaking.enums import SpeakingSkillType as ST
from app.services.language_speaking.enums import SpeakingTaskType as TT
from app.services.language_speaking_curriculum.catalog_builder import (
    N,
    _ev_fluency,
    _ev_function,
    _ev_interaction,
    _ev_phoneme,
    _ev_phrase,
    _ev_prosody,
    _ev_task,
    _ev_word,
    _fluency_mastery,
    _function_mastery,
    _goals_all,
    _goals_business,
    _goals_ielts,
    _goals_travel,
    _grammar_mastery,
    _interaction_mastery,
    _phoneme_mastery,
    _phrase_mastery,
    _prosody_mastery,
    _task_mastery,
    _word_mastery,
)
from app.services.language_speaking_curriculum.types import (
    SPEAKING_SKILL_GRAPH_VERSION,
    SPEAKING_SKILL_SCHEMA_VERSION,
    SpeakingSkillGraph,
    SpeakingSkillNode,
)


def _raw_nodes() -> list[SpeakingSkillNode]:
    """All catalog nodes — prerequisite edges only; next_skill_ids filled by _symmetrize."""
    nodes: list[SpeakingSkillNode] = []

    # ── 9. High-value pronunciation patterns ─────────────────────────────
    nodes += [
        N(
            "phoneme:theta",
            ST.phoneme,
            "Voiceless TH /θ/",
            "Produce /θ/ clearly for intelligibility (think, three, thank).",
            cefr_min=C.A1,
            cefr_max=C.B2,
            difficulty=2,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            functions=("articulation",),
            diagnostic_tags=("area:pronunciation", "contrast:theta"),
            remediation_tags=("misarticulation:theta",),
            is_root=True,
        ),
        N(
            "phoneme:eth",
            ST.phoneme,
            "Voiced TH /ð/",
            "Distinguish /ð/ in function words and content words (this, mother, breathe).",
            cefr_min=C.A1,
            cefr_max=C.B2,
            difficulty=2,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            functions=("articulation",),
            diagnostic_tags=("area:pronunciation", "contrast:eth"),
            remediation_tags=("misarticulation:eth",),
            is_root=True,
        ),
        N(
            "pattern:th_substitution",
            ST.pronunciation_pattern,
            "TH vs /s/ or /t/ substitution",
            "Diagnose and remediate common /θ/→/s/ or /t/ substitutions affecting clarity.",
            prereqs=("phoneme:theta",),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:substitution"),
            remediation_tags=("substitution:theta",),
            transfer_targets=("word:think", "word:three"),
        ),
        N(
            "phoneme:short_i",
            ST.phoneme,
            "Short vowel /ɪ/",
            "Distinguish /ɪ/ from /iː/ in high-frequency words (ship/sheep, sit/seat).",
            cefr_min=C.A1,
            cefr_max=C.B1,
            difficulty=2,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "contrast:short_i"),
            is_root=True,
        ),
        N(
            "pattern:vowel_length",
            ST.pronunciation_pattern,
            "Vowel length contrast",
            "Use vowel length contrasts to avoid meaning confusion in minimal pairs.",
            prereqs=("phoneme:short_i",),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:vowel_length"),
        ),
        N(
            "phoneme:ed_endings",
            ST.phoneme,
            "-ed past ending sounds",
            "Produce /t/, /d/, /ɪd/ allomorphs for regular past verbs.",
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "morphology:ed"),
            is_root=True,
        ),
        N(
            "pattern:word_stress",
            ST.pronunciation_pattern,
            "Word stress placement",
            "Place primary stress correctly on two- and three-syllable words.",
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_word_mastery(),
            evidence=_ev_word(),
            activities=(TT.pronunciation_drill, TT.shadowing),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:stress"),
            is_root=True,
        ),
        N(
            "pattern:schwa_unstressed",
            ST.pronunciation_pattern,
            "Unstressed schwa",
            "Reduce unstressed syllables with schwa for natural rhythm.",
            prereqs=("pattern:word_stress",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_word_mastery(),
            evidence=_ev_word(),
            activities=(TT.pronunciation_drill, TT.shadowing),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:schwa"),
        ),
        N(
            "pattern:linking_sounds",
            ST.pronunciation_pattern,
            "Linking and connected speech",
            "Link words smoothly without losing intelligibility.",
            prereqs=("pattern:word_stress", "pattern:schwa_unstressed"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_word_mastery(),
            evidence=_ev_word(),
            activities=(TT.shadowing,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:linking"),
        ),
        N(
            "pattern:connected_th",
            ST.pronunciation_pattern,
            "Connected speech TH",
            "Maintain /θ/ clarity in connected speech and multi-word phrases.",
            prereqs=("pattern:linking_sounds", "pattern:th_substitution"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.shadowing,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "pattern:connected_th"),
        ),
        N(
            "pattern:theta_phrase_drill",
            ST.pronunciation_pattern,
            "TH in short phrases",
            "Keep /θ/ intelligible in high-frequency phrases (I think, three times).",
            prereqs=("word:three", "pattern:connected_th"),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_phoneme_mastery(),
            evidence=_ev_phoneme(),
            activities=(TT.shadowing, TT.pronunciation_drill),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "chain:theta"),
        ),
    ]

    # ── 1. Opinion and reasoning chain ─────────────────────────────────────
    nodes += [
        N(
            "word:think",
            ST.word,
            "Word: think",
            "Produce 'think' with clear /θ/ in isolation and short phrases.",
            prereqs=("phoneme:theta", "pattern:th_substitution"),
            cefr_min=C.A1,
            cefr_max=C.B2,
            difficulty=2,
            mastery=_word_mastery(),
            evidence=_ev_word(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            functions=("lexical",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
            remediation_tags=("word:think",),
        ),
        N(
            "phrase:i_think",
            ST.phrase,
            "Phrase: I think…",
            "Use 'I think' as a discourse opener with correct rhythm and /θ/.",
            prereqs=("word:think",),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=2,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            functions=("discourse_opener",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
        ),
        N(
            "function:express_opinion",
            ST.speaking_function,
            "Express opinion",
            "State a personal opinion clearly with a simple reason.",
            prereqs=("phrase:i_think",),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.dialogue, TT.monologue),
            goals=_goals_all + (G.ielts,),
            functions=("express_opinion",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
            remediation_tags=("weak_opinion",),
        ),
        N(
            "function:support_opinion",
            ST.speaking_function,
            "Support opinion",
            "Give reasons and brief examples to support a stated opinion.",
            prereqs=("function:express_opinion",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.dialogue, TT.monologue),
            goals=_goals_all + (G.ielts, G.academic),
            functions=("support_opinion",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
        ),
        N(
            "skill:explain_reasoning",
            ST.speaking_function,
            "Explain reasoning",
            "Connect claim → reason → example in spoken explanations.",
            prereqs=("function:support_opinion",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue, TT.dialogue),
            goals=_goals_ielts + _goals_business,
            functions=("explain_reasoning",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
            transfer_targets=("task:debate", "task:ielts_extended_response"),
        ),
        N(
            "task:debate",
            ST.task_skill,
            "Structured debate turn",
            "Present and defend a position with counter-acknowledgment in a debate format.",
            prereqs=("skill:explain_reasoning", "fluency:pause_control"),
            cefr_min=C.B2,
            cefr_max=C.C2,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.dialogue, TT.role_play),
            goals=_goals_ielts + (G.academic,),
            functions=("argue", "counter_argue"),
            tasks=("debate",),
            diagnostic_tags=("area:opinion_reasoning", "chain:theta"),
        ),
    ]

    # ── 8. Core prosody / intonation ───────────────────────────────────────
    nodes += [
        N(
            "prosody:question_intonation",
            ST.prosody_skill,
            "Question intonation",
            "Use rising/falling intonation appropriately for yes/no vs wh- questions.",
            cefr_min=C.A1,
            cefr_max=C.B2,
            difficulty=2,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.pronunciation_drill, TT.dialogue),
            goals=_goals_all,
            functions=("intonation",),
            diagnostic_tags=("area:prosody", "chain:questions"),
            is_root=True,
        ),
        N(
            "prosody:sentence_stress",
            ST.prosody_skill,
            "Sentence stress",
            "Emphasize content words and de-emphasize function words for clarity.",
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.shadowing,),
            goals=_goals_all,
            diagnostic_tags=("area:prosody",),
            is_root=True,
        ),
        N(
            "prosody:intonation_contours",
            ST.prosody_skill,
            "Intonation contours",
            "Produce basic rising and falling contours on short utterances.",
            prereqs=("prosody:question_intonation",),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:prosody",),
        ),
        N(
            "prosody:polar_question_rhythm",
            ST.prosody_skill,
            "Polar question rhythm",
            "Apply rising contour consistently on yes/no questions.",
            prereqs=("prosody:intonation_contours",),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:prosody", "chain:questions"),
        ),
        N(
            "prosody:wh_question_fall",
            ST.prosody_skill,
            "Wh-question falling tone",
            "Use appropriate falling intonation on wh- questions.",
            prereqs=("prosody:polar_question_rhythm",),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:prosody", "chain:questions"),
        ),
        N(
            "prosody:thought_groups",
            ST.prosody_skill,
            "Thought groups and chunking",
            "Group words into meaningful chunks with appropriate pauses.",
            prereqs=("prosody:sentence_stress",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.shadowing, TT.monologue),
            goals=_goals_ielts,
            diagnostic_tags=("area:prosody", "area:fluency"),
        ),
        N(
            "prosody:emphasis_contrast",
            ST.prosody_skill,
            "Emphasis for contrast",
            "Use pitch and stress to highlight contrast (I said Tuesday, not Thursday).",
            prereqs=("prosody:thought_groups",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_prosody_mastery(),
            evidence=_ev_prosody(),
            activities=(TT.dialogue,),
            goals=_goals_business + _goals_ielts,
            diagnostic_tags=("area:prosody",),
        ),
    ]

    # ── 2. Questions and clarification chain ───────────────────────────────
    nodes += [
        N(
            "phrase:yes_no_questions",
            ST.phrase,
            "Yes/no questions",
            "Form and deliver yes/no questions with correct intonation.",
            prereqs=("prosody:question_intonation",),
            cefr_min=C.A1,
            cefr_max=C.A2,
            difficulty=2,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:questions_clarification", "chain:questions"),
        ),
        N(
            "phrase:wh_questions",
            ST.phrase,
            "Wh- questions",
            "Ask who/what/where/when/why/how questions with appropriate falling tone.",
            prereqs=("prosody:question_intonation", "phrase:yes_no_questions"),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=2,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:questions_clarification", "chain:questions"),
        ),
        N(
            "phrase:polite_questions",
            ST.phrase,
            "Polite questions",
            "Use polite forms (Could you…, Would you mind…) in service contexts.",
            prereqs=("phrase:yes_no_questions",),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.role_play, TT.dialogue),
            goals=_goals_travel + (G.business,),
            diagnostic_tags=("area:questions_clarification", "chain:questions", "area:travel_service"),
        ),
        N(
            "function:clarification_request",
            ST.speaking_function,
            "Clarification requests",
            "Ask for repetition, slower speech, or meaning clarification appropriately.",
            prereqs=("phrase:polite_questions", "phrase:wh_questions"),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.dialogue, TT.role_play),
            goals=_goals_travel + _goals_all,
            functions=("clarification_request",),
            diagnostic_tags=("area:questions_clarification", "chain:questions"),
            remediation_tags=("breakdown_repair",),
        ),
        N(
            "interaction:interactive_conversation",
            ST.interaction_skill,
            "Interactive conversation",
            "Maintain a back-and-forth exchange with relevant responses and repair.",
            prereqs=("function:clarification_request", "fluency:response_timing"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_interaction_mastery(),
            evidence=_ev_interaction(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            functions=("interaction",),
            diagnostic_tags=("area:questions_clarification", "chain:questions"),
        ),
    ]

    # ── 3. Past events and storytelling ────────────────────────────────────
    nodes += [
        N(
            "grammar:past_tense_control",
            ST.grammar_structure,
            "Past tense control",
            "Use past simple (and past continuous where needed) accurately in speech.",
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_grammar_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_all,
            diagnostic_tags=("area:past_narrative", "chain:past"),
            is_root=True,
        ),
        N(
            "phrase:past_event_sentence",
            ST.phrase,
            "Past event sentence",
            "Describe a single past event in one or two clear sentences.",
            prereqs=("grammar:past_tense_control", "phoneme:ed_endings"),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.monologue,),
            goals=_goals_all,
            diagnostic_tags=("area:past_narrative", "chain:past"),
        ),
        N(
            "skill:sequence_events",
            ST.speaking_function,
            "Sequence events",
            "Order past events with sequencers (first, then, after that, finally).",
            prereqs=("phrase:past_event_sentence",),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_all,
            functions=("sequence",),
            diagnostic_tags=("area:past_narrative", "chain:past"),
        ),
        N(
            "skill:tell_story",
            ST.speaking_function,
            "Tell a short story",
            "Narrate a short personal story with beginning, middle, and end.",
            prereqs=("skill:sequence_events", "prosody:thought_groups"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_all + (G.ielts,),
            functions=("narrate",),
            diagnostic_tags=("area:past_narrative", "chain:past"),
        ),
        N(
            "task:extended_narrative",
            ST.task_skill,
            "Extended narrative",
            "Deliver a 1–2 minute coherent narrative with detail and temporal organization.",
            prereqs=("skill:tell_story", "fluency:extended_speech"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.monologue,),
            goals=_goals_ielts + _goals_all,
            tasks=("extended_narrative",),
            diagnostic_tags=("area:past_narrative", "chain:past"),
        ),
    ]

    # ── 7. Core fluency control ────────────────────────────────────────────
    nodes += [
        N(
            "fluency:appropriate_rate",
            ST.fluency_skill,
            "Appropriate speaking rate",
            "Maintain a listener-friendly speaking rate without rushing or dragging.",
            cefr_min=C.A2,
            cefr_max=C.C1,
            difficulty=2,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.monologue, TT.dialogue),
            goals=_goals_all,
            diagnostic_tags=("area:fluency",),
            is_root=True,
        ),
        N(
            "fluency:pause_control",
            ST.fluency_skill,
            "Pause control",
            "Use pauses at clause boundaries; reduce mid-clause hesitations.",
            prereqs=("fluency:appropriate_rate",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=3,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.monologue,),
            goals=_goals_all + _goals_ielts,
            diagnostic_tags=("area:fluency",),
        ),
        N(
            "fluency:response_timing",
            ST.fluency_skill,
            "Response timing",
            "Respond within conversational time windows without long silent gaps.",
            prereqs=("fluency:appropriate_rate",),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:fluency", "area:questions_clarification"),
        ),
        N(
            "fluency:extended_speech",
            ST.fluency_skill,
            "Extended speech fluency",
            "Sustain intelligible speech for 60+ seconds with manageable hesitations.",
            prereqs=("fluency:pause_control", "prosody:thought_groups"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.monologue,),
            goals=_goals_ielts,
            diagnostic_tags=("area:fluency",),
        ),
        N(
            "fluency:ielts_time_pressure",
            ST.fluency_skill,
            "Fluency under time pressure",
            "Maintain coherence and rate in timed IELTS-style responses.",
            prereqs=("fluency:extended_speech",),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.monologue, TT.interview),
            goals=_goals_ielts,
            diagnostic_tags=("area:fluency", "area:ielts_extended"),
        ),
    ]

    # ── 4. Service / travel interaction ────────────────────────────────────
    nodes += [
        N(
            "phrase:travel_greetings",
            ST.phrase,
            "Travel greetings",
            "Greet and introduce yourself in travel/service encounters.",
            cefr_min=C.A1,
            cefr_max=C.A2,
            difficulty=1,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.role_play,),
            goals=_goals_travel,
            diagnostic_tags=("area:travel_service",),
            is_root=True,
        ),
        N(
            "function:make_request",
            ST.speaking_function,
            "Make a polite request",
            "Request information, objects, or help politely in service settings.",
            prereqs=("phrase:travel_greetings", "phrase:polite_questions"),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.role_play,),
            goals=_goals_travel,
            functions=("request",),
            diagnostic_tags=("area:travel_service",),
        ),
        N(
            "function:understand_and_repair",
            ST.speaking_function,
            "Understand and repair breakdown",
            "Confirm understanding and repair communication breakdowns while traveling.",
            prereqs=("function:clarification_request", "function:make_request"),
            cefr_min=C.A2,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.role_play, TT.dialogue),
            goals=_goals_travel,
            functions=("repair",),
            diagnostic_tags=("area:travel_service",),
            remediation_tags=("breakdown_repair",),
        ),
        N(
            "task:service_interaction",
            ST.task_skill,
            "Service interaction role-play",
            "Complete a full service encounter (hotel, transport, shop) with repair strategies.",
            prereqs=("function:understand_and_repair", "interaction:interactive_conversation"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_task_mastery(),
            evidence=_ev_task(),
            activities=(TT.role_play,),
            goals=_goals_travel,
            tasks=("service_interaction",),
            diagnostic_tags=("area:travel_service",),
        ),
    ]

    # ── 5. Professional / business speaking ────────────────────────────────
    nodes += [
        N(
            "phrase:professional_introduction",
            ST.phrase,
            "Professional introduction",
            "Introduce role, team, and purpose in a professional context.",
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.role_play, TT.interview),
            goals=_goals_business,
            diagnostic_tags=("area:business_professional",),
            is_root=True,
        ),
        N(
            "function:professional_explanation",
            ST.speaking_function,
            "Professional explanation",
            "Explain a work process or decision clearly for colleagues.",
            prereqs=("phrase:professional_introduction", "skill:explain_reasoning"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue, TT.dialogue),
            goals=_goals_business,
            functions=("explain",),
            diagnostic_tags=("area:business_professional",),
        ),
        N(
            "function:meeting_contribution",
            ST.speaking_function,
            "Meeting contribution",
            "Contribute relevant points and acknowledge others in meetings.",
            prereqs=("function:professional_explanation", "interaction:interactive_conversation"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_interaction_mastery(),
            evidence=_ev_interaction(),
            activities=(TT.dialogue, TT.role_play),
            goals=_goals_business,
            functions=("meeting",),
            diagnostic_tags=("area:business_professional",),
        ),
        N(
            "function:proposal_language",
            ST.speaking_function,
            "Proposal language",
            "Present suggestions with benefits, risks, and next steps.",
            prereqs=("function:meeting_contribution", "function:support_opinion"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue, TT.dialogue),
            goals=_goals_business,
            functions=("propose",),
            diagnostic_tags=("area:business_professional",),
        ),
        N(
            "task:structured_business_response",
            ST.task_skill,
            "Structured business response",
            "Deliver a structured spoken response (situation → action → result) in professional contexts.",
            prereqs=("function:proposal_language", "fluency:pause_control"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.interview, TT.monologue),
            goals=_goals_business + (G.job_interview,),
            tasks=("structured_response",),
            diagnostic_tags=("area:business_professional",),
        ),
        N(
            "task:job_interview_answer",
            ST.task_skill,
            "Job interview answer",
            "Answer behavioral interview questions with clear structure and relevance.",
            prereqs=("task:structured_business_response", "skill:explain_reasoning"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.interview,),
            goals=(G.job_interview, G.business),
            tasks=("job_interview",),
            diagnostic_tags=("area:business_professional",),
        ),
    ]

    # ── 6. Extended IELTS-style responses (multi-family prerequisites) ─────
    nodes += [
        N(
            "skill:topic_development",
            ST.speaking_function,
            "Topic development",
            "Expand a topic with relevant details without losing focus.",
            prereqs=("function:support_opinion", "fluency:extended_speech"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_ielts,
            functions=("topic_development",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "skill:spoken_organization",
            ST.speaking_function,
            "Spoken organization",
            "Organize spoken answers with clear opening, body, and closing.",
            prereqs=("skill:sequence_events", "prosody:thought_groups"),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_ielts,
            functions=("organize",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "task:ielts_part1_response",
            ST.task_skill,
            "IELTS Part 1 response",
            "Answer familiar-topic questions with appropriate length and clarity.",
            prereqs=("function:express_opinion", "fluency:response_timing"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_task_mastery(),
            evidence=_ev_task(),
            activities=(TT.interview,),
            goals=_goals_ielts,
            tasks=("ielts_part1",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "skill:ielts_coherence_markers",
            ST.speaking_function,
            "IELTS coherence markers",
            "Use spoken discourse markers (firstly, moreover, in conclusion) to structure long answers.",
            prereqs=("skill:topic_development", "skill:spoken_organization"),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue,),
            goals=_goals_ielts,
            functions=("discourse_markers",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "task:ielts_part2_cue_card",
            ST.task_skill,
            "IELTS Part 2 cue card",
            "Speak for 1–2 minutes on a cue card with notes and clear structure.",
            prereqs=(
                "skill:ielts_coherence_markers",
                "fluency:ielts_time_pressure",
            ),
            cefr_min=C.B2,
            cefr_max=C.C1,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.monologue, TT.interview),
            goals=_goals_ielts,
            tasks=("ielts_part2",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "task:ielts_extended_response",
            ST.task_skill,
            "IELTS extended response",
            "Synthesize opinion, support, fluency, and organization in an extended spoken answer.",
            prereqs=(
                "task:ielts_part2_cue_card",
                "skill:explain_reasoning",
                "function:support_opinion",
                "fluency:ielts_time_pressure",
                "skill:spoken_organization",
            ),
            cefr_min=C.B2,
            cefr_max=C.C2,
            difficulty=5,
            mastery=_task_mastery(extended=True),
            evidence=_ev_task(extended=True),
            activities=(TT.monologue, TT.interview),
            goals=_goals_ielts,
            tasks=("ielts_extended",),
            diagnostic_tags=("area:ielts_extended",),
        ),
    ]

    # ── Additional vocabulary-function and conversation nodes ─────────────
    nodes += [
        N(
            "vocab:function:agree_disagree",
            ST.vocabulary_function,
            "Agree and disagree",
            "Use functional phrases to agree, partially agree, or disagree politely.",
            prereqs=("function:express_opinion",),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=3,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            functions=("agree", "disagree"),
            diagnostic_tags=("area:opinion_reasoning",),
        ),
        N(
            "conversation:small_talk",
            ST.conversation_skill,
            "Small talk",
            "Sustain brief social conversation on familiar topics.",
            prereqs=("interaction:interactive_conversation", "phrase:travel_greetings"),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=3,
            mastery=_interaction_mastery(),
            evidence=_ev_interaction(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:questions_clarification",),
        ),
        N(
            "conversation:topic_maintenance",
            ST.conversation_skill,
            "Topic maintenance",
            "Keep a conversation on topic and invite the partner to contribute.",
            prereqs=("conversation:small_talk", "skill:topic_development"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_interaction_mastery(),
            evidence=_ev_interaction(),
            activities=(TT.dialogue,),
            goals=_goals_all + _goals_ielts,
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "word:three",
            ST.word,
            "Word: three",
            "Produce 'three' with clear /θ/ — common substitution diagnostic anchor.",
            prereqs=("phoneme:theta", "pattern:th_substitution"),
            cefr_min=C.A1,
            cefr_max=C.A2,
            difficulty=2,
            mastery=_word_mastery(),
            evidence=_ev_word(),
            activities=(TT.pronunciation_drill,),
            goals=_goals_all,
            diagnostic_tags=("area:pronunciation", "chain:theta"),
        ),
        N(
            "phrase:because_reason",
            ST.phrase,
            "Because + reason",
            "Attach a simple reason clause with 'because' in spoken answers.",
            prereqs=("function:express_opinion",),
            cefr_min=C.A2,
            cefr_max=C.B1,
            difficulty=2,
            mastery=_phrase_mastery(),
            evidence=_ev_phrase(),
            activities=(TT.dialogue,),
            goals=_goals_all,
            diagnostic_tags=("area:opinion_reasoning",),
        ),
        N(
            "grammar:present_perfect_experience",
            ST.grammar_structure,
            "Present perfect for experience",
            "Talk about life experience with present perfect forms in speech.",
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_grammar_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue, TT.interview),
            goals=_goals_ielts + _goals_all,
            diagnostic_tags=("area:ielts_extended",),
            is_root=True,
        ),
        N(
            "task:picture_description",
            ST.task_skill,
            "Picture description",
            "Describe a visual scene with location, action, and detail.",
            prereqs=("skill:spoken_organization", "fluency:extended_speech"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_task_mastery(),
            evidence=_ev_task(),
            activities=(TT.picture_description,),
            goals=_goals_ielts + _goals_all,
            tasks=("picture_description",),
            diagnostic_tags=("area:ielts_extended",),
        ),
        N(
            "fluency:filler_reduction",
            ST.fluency_skill,
            "Filler reduction",
            "Reduce excessive fillers (um, uh, like) while maintaining natural pace.",
            prereqs=("fluency:pause_control",),
            cefr_min=C.B1,
            cefr_max=C.C1,
            difficulty=3,
            mastery=_fluency_mastery(),
            evidence=_ev_fluency(),
            activities=(TT.monologue,),
            goals=_goals_ielts + _goals_business,
            diagnostic_tags=("area:fluency",),
        ),
        N(
            "function:compare_contrast",
            ST.speaking_function,
            "Compare and contrast",
            "Compare two options orally with clear criteria.",
            prereqs=("function:support_opinion", "grammar:past_tense_control"),
            cefr_min=C.B1,
            cefr_max=C.B2,
            difficulty=4,
            mastery=_function_mastery(),
            evidence=_ev_function(),
            activities=(TT.monologue, TT.dialogue),
            goals=_goals_ielts + (G.academic,),
            functions=("compare", "contrast"),
            diagnostic_tags=("area:opinion_reasoning", "area:ielts_extended"),
        ),
    ]

    return nodes


def _symmetrize_next_skills(nodes: list[SpeakingSkillNode]) -> tuple[SpeakingSkillNode, ...]:
    """Derive next_skill_ids from prerequisite edges and validate symmetry."""
    by_id = {n.skill_id: n for n in nodes}
    next_map: dict[str, set[str]] = {n.skill_id: set(n.next_skill_ids) for n in nodes}

    for node in nodes:
        for prereq in node.prerequisite_skill_ids:
            next_map.setdefault(prereq, set()).add(node.skill_id)

    rebuilt: list[SpeakingSkillNode] = []
    for node in nodes:
        nxt = tuple(sorted(next_map.get(node.skill_id, set())))
        rebuilt.append(
            SpeakingSkillNode(
                skill_id=node.skill_id,
                skill_type=node.skill_type,
                label=node.label,
                description=node.description,
                cefr_min=node.cefr_min,
                cefr_max=node.cefr_max,
                prerequisite_skill_ids=node.prerequisite_skill_ids,
                next_skill_ids=nxt,
                related_skill_ids=node.related_skill_ids,
                difficulty=node.difficulty,
                mastery_requirements=node.mastery_requirements,
                evidence_requirements=node.evidence_requirements,
                recommended_activity_types=node.recommended_activity_types,
                spaced_repetition_profile=node.spaced_repetition_profile,
                goal_relevance=node.goal_relevance,
                speaking_functions=node.speaking_functions,
                task_relevance=node.task_relevance,
                diagnostic_tags=node.diagnostic_tags,
                remediation_tags=node.remediation_tags,
                transfer_targets=node.transfer_targets,
                is_root=node.is_root,
            )
        )
    return tuple(rebuilt)


def build_speaking_skill_graph() -> SpeakingSkillGraph:
    """Build and return the validated v1 speaking skill graph."""
    raw = _raw_nodes()
    # Deduplicate by skill_id (last wins — should not happen)
    by_id: dict[str, SpeakingSkillNode] = {}
    for node in raw:
        by_id[node.skill_id] = node
    nodes = _symmetrize_next_skills(list(by_id.values()))
    return SpeakingSkillGraph(
        version=SPEAKING_SKILL_GRAPH_VERSION,
        schema_version=SPEAKING_SKILL_SCHEMA_VERSION,
        nodes=nodes,
    )


# Module-level singleton for import convenience
SPEAKING_SKILL_GRAPH: SpeakingSkillGraph = build_speaking_skill_graph()
